// Browser glue for the converter page's "Custom WebGPU kernels" panel.
//
// Lists every node in a model that carries a custom WebGPU program attached
// via onnxsim.webgpu_kernel_metadata (hand-written, or generated by
// onnxsim.webgpu_tinygrad_codegen) -- read-only: this only *displays*
// whatever a model already carries, via the same readWebgpuKernelSpecs a
// real dispatcher would use (see webgpu_kernel_annotations.mjs's own
// docstring for what this deliberately does not do -- detect gaps or
// generate a kernel itself).
//
// Wiring mirrors the "Dynamic dimensions" panel (shapes_view.mjs): the
// "before" side watches the file input directly and exposes a
// `window.webgpuKernelsShowBefore(bytes, name)` hook for Hugging Face loads
// (which bypass the file input); the "after" side is driven by
// `window.webgpuKernelsShowAfter(dataUrl, name)`, called from the converter
// worker glue in index.html once a conversion finishes -- useful since
// simplify/optimize can rename or fuse away an annotated node, so "after"
// is not always the same list as "before".

import { dataUrlToArrayBuffer } from "./netron.mjs";
import { listWebgpuKernelAnnotations } from "./webgpu_kernel_annotations.mjs";

// Latest parsed annotations for each side; null until a model arrives there,
// [] once parsed with nothing found.
const state = { before: null, after: null };

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// One step's own <details> block: entry point/dispatch/bindings summary
// line, with the raw WGSL source collapsed inside (can be long).
function stepHtml(step) {
  const bindings = step.bindings.map((b) => `<code>${esc(b)}</code>`).join(", ");
  return (
    `<details class="wk-step">` +
    `<summary>step ${step.index}: <code>${esc(step.entryPoint)}</code> — ` +
    `dispatch [${step.dispatch.join(", ")}] — ${step.bindings.length} binding(s)</summary>` +
    `<div class="wk-bindings">${bindings}</div>` +
    `<pre class="wk-wgsl">${esc(step.wgsl)}</pre>` +
    `</details>`
  );
}

function annotationHtml(a) {
  const intermediateNote = a.intermediateCount
    ? ` — ${a.intermediateCount} intermediate buffer(s): ` +
      Object.entries(a.intermediates)
        .map(([name, bytes]) => `<code>${esc(name)}</code> (${bytes}B)`)
        .join(", ")
    : "";
  return (
    `<div class="wk-node">` +
    `<div class="wk-node-head"><code>${esc(a.nodeName)}</code> — ` +
    `${a.stepCount} step(s)${intermediateNote}</div>` +
    a.steps.map(stepHtml).join("") +
    `</div>`
  );
}

function paneHtml(title, annotations) {
  if (!annotations) {
    return `<div class="wk-pane"><div class="wk-head">${esc(title)}</div><em>—</em></div>`;
  }
  if (annotations.length === 0) {
    return `<div class="wk-pane"><div class="wk-head">${esc(title)}</div><em>no custom WebGPU kernels attached</em></div>`;
  }
  return (
    `<div class="wk-pane"><div class="wk-head">${esc(title)}</div>` +
    annotations.map(annotationHtml).join("") +
    `</div>`
  );
}

function render() {
  const container = document.getElementById("webgpu-kernels-content");
  if (!container) return;
  container.innerHTML = `<div class="wk-panes">${paneHtml("Before", state.before)}${paneHtml("After", state.after)}</div>`;
}

// Parse model bytes (Uint8Array | ArrayBuffer) into annotations for one side
// and re-render. Never throws out to the caller -- a parse failure just
// clears that side, so a malformed model can't take the panel (or its host
// page) down.
function setSide(which, data) {
  try {
    const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    state[which] = listWebgpuKernelAnnotations(bytes);
  } catch (err) {
    console.error(`webgpu kernels (${which}):`, err);
    state[which] = null;
  }
  render();
}

function initWebgpuKernelsPanel() {
  render(); // draw the empty placeholder up front

  const fileInput = document.getElementById("file-input");
  if (fileInput) {
    fileInput.addEventListener("change", async (e) => {
      const file = e.target.files && e.target.files[0];
      if (!file) return;
      // A new upload invalidates the previous "after" listing until the
      // conversion for this model finishes.
      state.after = null;
      try {
        setSide("before", new Uint8Array(await file.arrayBuffer()));
      } catch (err) {
        console.error("webgpu kernels (before):", err);
      }
    });
  }

  // Hugging Face downloads bypass the file input; the loader drives us here.
  window.webgpuKernelsShowBefore = (data, _name) => {
    state.after = null;
    setSide("before", data);
  };

  // Called by the converter worker glue in index.html when a result is ready.
  window.webgpuKernelsShowAfter = (dataUrl, _name) => {
    try {
      setSide("after", dataUrlToArrayBuffer(dataUrl));
    } catch (err) {
      console.error("webgpu kernels (after):", err);
    }
  };
}

initWebgpuKernelsPanel();
