// Browser glue for the converter page's "Custom WebGPU kernels" panel.
//
// Lists every node in a model that carries a custom WebGPU program attached
// via onnxsim.webgpu_kernel_metadata (hand-written, or generated by
// onnxsim.webgpu_tinygrad_codegen), via the same readWebgpuKernelSpecs a
// real dispatcher would use (see webgpu_kernel_annotations.mjs's own
// docstring for the pure reshaping logic this delegates to).
//
// Display is still entirely passive -- this does not run
// onnxsim.webgpu_target's own gap detection, and never generates or
// dispatches anything on its own. The one exception, opt-in only, is the
// "Tune this kernel" button on a Conv node's own entry: click it and
// webgpu_kernel_tuner.mjs runs the real browser-timed tuning loop (Pyodide +
// tinygrad, live, against a real WebGPU device -- see that module's own
// docstring for scope and why it's opt-in, not automatic) and offers an
// "Export tuned model" download once a winner is picked, via
// onnx_metadata_writer.mjs's attachWebgpuKernelSpec. Nothing here changes
// what Simplify/Optimize themselves produce; a tuned export is a separate
// download the visitor asks for.
//
// Wiring mirrors the "Dynamic dimensions" panel (shapes_view.mjs): the
// "before" side watches the file input directly and exposes a
// `window.webgpuKernelsShowBefore(bytes, name)` hook for Hugging Face loads
// (which bypass the file input); the "after" side is driven by
// `window.webgpuKernelsShowAfter(dataUrl, name)`, called from the converter
// worker glue in index.html once a conversion finishes -- useful since
// simplify/optimize can rename or fuse away an annotated node, so "after"
// is not always the same list as "before".

import { dataUrlToArrayBuffer } from "./netron.mjs";
import { listWebgpuKernelAnnotations } from "./webgpu_kernel_annotations.mjs";
import { downloadBytes } from "./download.mjs";
import { attachWebgpuKernelSpec } from "./onnx_metadata_writer.mjs";

// Latest parsed state for each side: null until a model arrives there,
// {bytes, name, annotations} once parsed (annotations is [] when nothing
// found). Bytes are kept (not just the display summary) so a "Tune"/"Export"
// action has something to tune/attach onto.
const state = { before: null, after: null };

// Tuning progress/results, keyed by `${which}:${nodeName}` so the "before"
// and "after" sides (or two different nodes) never share one run's state.
// {status: "idle"|"running"|"done"|"error", log: string[], result: object|null,
//  error: string|null}
const tuning = new Map();

function tuneKey(which, nodeName) {
  return `${which}:${nodeName}`;
}

function tuningStateFor(which, nodeName) {
  const key = tuneKey(which, nodeName);
  if (!tuning.has(key)) {
    tuning.set(key, { status: "idle", log: [], result: null, error: null });
  }
  return tuning.get(key);
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// One step's own <details> block: entry point/dispatch/bindings summary
// line, with the raw WGSL source collapsed inside (can be long).
function stepHtml(step) {
  const bindings = step.bindings.map((b) => `<code>${esc(b)}</code>`).join(", ");
  return (
    `<details class="wk-step">` +
    `<summary>step ${step.index}: <code>${esc(step.entryPoint)}</code> — ` +
    `dispatch [${step.dispatch.join(", ")}] — ${step.bindings.length} binding(s)</summary>` +
    `<div class="wk-bindings">${bindings}</div>` +
    `<pre class="wk-wgsl">${esc(step.wgsl)}</pre>` +
    `</details>`
  );
}

function tuneResultHtml(which, nodeName, t) {
  if (t.status === "idle") {
    return `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Tune this kernel…</button>`;
  }
  const log = t.log.length ? `<div class="wk-tune-log">${t.log.map((l) => esc(l)).join("<br>")}</div>` : "";
  if (t.status === "running") {
    return `<div class="wk-tune-status">Tuning…</div>${log}`;
  }
  if (t.status === "error") {
    return (
      `<div class="wk-tune-status wk-tune-error">Tuning failed: ${esc(t.error)}</div>${log}` +
      `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Try again</button>`
    );
  }
  // done
  const { results, winner } = t.result;
  const rows = results
    .map((r, i) => {
      const cls = r === winner ? "wk-tune-winner" : "";
      const gpu = r.gpuDurationNs !== null ? ` (GPU: ${(r.gpuDurationNs / 1e6).toFixed(3)}ms)` : "";
      return (
        `<tr class="${cls}"><td>${i === 0 ? "★" : ""}</td>` +
        `<td><code>${esc(r.appliedOpts)}</code></td>` +
        `<td>${r.medianMs.toFixed(3)}ms${gpu}</td></tr>`
      );
    })
    .join("");
  return (
    `${log}` +
    `<table class="wk-tune-table"><thead><tr><th></th><th>applied opts</th><th>median time</th></tr></thead>` +
    `<tbody>${rows}</tbody></table>` +
    `<button type="button" class="wk-tune-btn" data-action="export" data-which="${esc(which)}" data-node="${esc(nodeName)}">Export tuned model (winner) ↓</button> ` +
    `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Re-tune</button>`
  );
}

function annotationHtml(a, which) {
  const intermediateNote = a.intermediateCount
    ? ` — ${a.intermediateCount} intermediate buffer(s): ` +
      Object.entries(a.intermediates)
        .map(([name, bytes]) => `<code>${esc(name)}</code> (${bytes}B)`)
        .join(", ")
    : "";
  const t = tuningStateFor(which, a.nodeName);
  return (
    `<div class="wk-node">` +
    `<div class="wk-node-head"><code>${esc(a.nodeName)}</code> — ` +
    `${a.stepCount} step(s)${intermediateNote}</div>` +
    a.steps.map(stepHtml).join("") +
    `<div class="wk-tune">${tuneResultHtml(which, a.nodeName, t)}</div>` +
    `</div>`
  );
}

function paneHtml(title, which, side) {
  if (!side) {
    return `<div class="wk-pane"><div class="wk-head">${esc(title)}</div><em>—</em></div>`;
  }
  if (side.annotations.length === 0) {
    return `<div class="wk-pane"><div class="wk-head">${esc(title)}</div><em>no custom WebGPU kernels attached</em></div>`;
  }
  return (
    `<div class="wk-pane"><div class="wk-head">${esc(title)}</div>` +
    side.annotations.map((a) => annotationHtml(a, which)).join("") +
    `</div>`
  );
}

function render() {
  const container = document.getElementById("webgpu-kernels-content");
  if (!container) return;
  container.innerHTML = `<div class="wk-panes">${paneHtml("Before", "before", state.before)}${paneHtml("After", "after", state.after)}</div>`;
}

// Parse model bytes (Uint8Array | ArrayBuffer) into annotations for one side
// and re-render. Never throws out to the caller -- a parse failure just
// clears that side, so a malformed model can't take the panel (or its host
// page) down.
function setSide(which, data, name) {
  try {
    const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    state[which] = { bytes, name: name || "model.onnx", annotations: listWebgpuKernelAnnotations(bytes) };
  } catch (err) {
    console.error(`webgpu kernels (${which}):`, err);
    state[which] = null;
  }
  // A freshly (re)loaded side starts with no tuning history of its own --
  // otherwise a stale winner from a previous file could get exported onto
  // an unrelated model that happens to share a node name.
  for (const key of [...tuning.keys()]) {
    if (key.startsWith(`${which}:`)) tuning.delete(key);
  }
  render();
}

// Lazily creates (and caches) one WebGPU device, shared by every tuning run
// on this page -- matches the pattern the webgpu_kernel_tuning*.test.mjs
// files use, requesting the timestamp-query feature when available so GPU
// durations show up alongside the wall-clock ones tuneConvKernel always
// reports.
let devicePromise = null;
function getWebgpuDevice() {
  if (!devicePromise) {
    devicePromise = (async () => {
      if (!navigator.gpu) {
        throw new Error("WebGPU is not available in this browser");
      }
      const adapter = await navigator.gpu.requestAdapter();
      if (!adapter) throw new Error("no WebGPU adapter available");
      const wantTimestamps = adapter.features.has("timestamp-query");
      return adapter.requestDevice({ requiredFeatures: wantTimestamps ? ["timestamp-query"] : [] });
    })().catch((err) => {
      devicePromise = null;
      throw err;
    });
  }
  return devicePromise;
}

async function handleTuneClick(which, nodeName) {
  const side = state[which];
  if (!side) return;
  const t = tuningStateFor(which, nodeName);
  if (t.status === "running") return;
  t.status = "running";
  t.log = [];
  t.error = null;
  t.result = null;
  render();

  try {
    const { tuneConvKernel } = await import("./webgpu_kernel_tuner.mjs");
    const device = await getWebgpuDevice();
    const result = await tuneConvKernel(device, side.bytes, nodeName, {
      onProgress: (msg) => {
        t.log.push(msg);
        render();
      },
    });
    t.status = "done";
    t.result = result;
    // Test-observability only (mirrors window.__onnxsimConverted's own
    // precedent) -- nothing reads this at runtime.
    window.__wkLastTuneResult = { which, nodeName, result };
  } catch (err) {
    console.error(`webgpu kernel tuner (${which}/${nodeName}):`, err);
    t.status = "error";
    t.error = (err && err.message) || String(err);
  }
  render();
}

function handleExportClick(which, nodeName) {
  const side = state[which];
  const t = tuningStateFor(which, nodeName);
  if (!side || t.status !== "done" || !t.result) return;
  try {
    const updated = attachWebgpuKernelSpec(side.bytes, nodeName, t.result.winner.spec);
    const base = side.name.replace(/\.onnx$/i, "");
    downloadBytes(updated, `${base}.tuned.onnx`);
  } catch (err) {
    console.error(`webgpu kernel export (${which}/${nodeName}):`, err);
    t.status = "error";
    t.error = `export failed: ${(err && err.message) || err}`;
    render();
  }
}

function initWebgpuKernelsPanel() {
  render(); // draw the empty placeholder up front

  const container = document.getElementById("webgpu-kernels-content");
  if (container) {
    container.addEventListener("click", (e) => {
      const btn = e.target.closest("button[data-action]");
      if (!btn) return;
      const { action, which, node } = btn.dataset;
      if (action === "tune") handleTuneClick(which, node);
      else if (action === "export") handleExportClick(which, node);
    });
  }

  const fileInput = document.getElementById("file-input");
  if (fileInput) {
    fileInput.addEventListener("change", async (e) => {
      const file = e.target.files && e.target.files[0];
      if (!file) return;
      // A new upload invalidates the previous "after" listing until the
      // conversion for this model finishes.
      state.after = null;
      try {
        setSide("before", new Uint8Array(await file.arrayBuffer()), file.name);
      } catch (err) {
        console.error("webgpu kernels (before):", err);
      }
    });
  }

  // Hugging Face downloads bypass the file input; the loader drives us here.
  window.webgpuKernelsShowBefore = (data, name) => {
    state.after = null;
    setSide("before", data, name);
  };

  // Called by the converter worker glue in index.html when a result is ready.
  window.webgpuKernelsShowAfter = (dataUrl, name) => {
    try {
      setSide("after", dataUrlToArrayBuffer(dataUrl), name);
    } catch (err) {
      console.error("webgpu kernels (after):", err);
    }
  };
}

initWebgpuKernelsPanel();
