// Browser glue for the converter page's "Custom WebGPU kernels" panel.
//
// Lists every node in a model that carries a custom WebGPU program attached
// via onnxsim.webgpu_kernel_metadata (hand-written, or generated by
// onnxsim.webgpu_tinygrad_codegen), via the same readWebgpuKernelSpecs a
// real dispatcher would use (see webgpu_kernel_annotations.mjs's own
// docstring for the pure reshaping logic this delegates to).
//
// Display of *already-attached* kernels is still entirely passive -- this
// does not run onnxsim.webgpu_target's own gap detection. The opt-in part is
// the "Tune this kernel" button: click it and webgpu_kernel_tuner.mjs runs
// the real browser-timed tuning loop (Pyodide + tinygrad, live, against a
// real WebGPU device -- see that module's own docstring for scope and why
// it's opt-in, not automatic) and offers an "Export tuned model" download
// once a winner is picked, via onnx_metadata_writer.mjs's
// attachWebgpuKernelSpec. This button isn't limited to nodes that already
// carry a kernel spec -- onnxsim.webgpu_tinygrad_codegen's own server-side
// gap-flagging only ever attaches one to the narrow Conv3D/align_corners-
// Resize gaps onnxsim.webgpu_target detects, so almost no ordinary uploaded
// model has any pre-attached kernel at all. `onnx_conv_node_reader.mjs`'s
// listConvNodeNames lists every Conv node in the graph instead, and this
// view offers the same tune UI on any of them that isn't already shown
// above (see setSide's own comment). A **"Tune full graph…"** button per
// side (see fullGraphSectionHtml/handleTuneFullGraphClick) tunes every Conv
// node one after another instead of clicking each one by hand -- it drives
// the exact same per-node state a single click would, so each node's own
// card updates live as the batch works through it, then one "Export full
// graph" button chains attachWebgpuKernelSpec across every node that
// succeeded into a single download. Pyodide/tinygrad load once and stay
// cached across nodes, but each node's own GPU dispatch loop still costs
// real time, so this can take a while on a model with many Conv nodes -- a
// node that fails to tune (non-static shape, more than one scheduled kernel
// call, ...) is recorded on its own card and the batch moves on, it doesn't
// abort the rest of the graph. Nothing here changes what Simplify/Optimize
// themselves produce; a tuned export is a separate download the visitor
// asks for.
//
// Wiring mirrors the "Dynamic dimensions" panel (shapes_view.mjs): the
// "before" side watches the file input directly and exposes a
// `window.webgpuKernelsShowBefore(bytes, name)` hook for Hugging Face loads
// (which bypass the file input); the "after" side is driven by
// `window.webgpuKernelsShowAfter(dataUrl, name)`, called from the converter
// worker glue in index.html once a conversion finishes -- useful since
// simplify/optimize can rename or fuse away an annotated node, so "after"
// is not always the same list as "before".

import { dataUrlToArrayBuffer } from "./netron.mjs";
import { listWebgpuKernelAnnotations } from "./webgpu_kernel_annotations.mjs";
import { downloadBytes } from "./download.mjs";
import { attachWebgpuKernelSpec } from "./onnx_metadata_writer.mjs";
import { listConvNodeNames } from "./onnx_conv_node_reader.mjs";

// Latest parsed state for each side: null until a model arrives there,
// {bytes, name, annotations, tunableConvNodes} once parsed (annotations is
// [] when nothing found; tunableConvNodes is every Conv node NOT already in
// annotations -- see setSide's own comment on why this list exists at all).
// Bytes are kept (not just the display summary) so a "Tune"/"Export" action
// has something to tune/attach onto.
const state = { before: null, after: null };

// Tuning progress/results, keyed by `${which}:${nodeName}` so the "before"
// and "after" sides (or two different nodes) never share one run's state.
// {status: "idle"|"running"|"done"|"error", log: string[], result: object|null,
//  error: string|null}
const tuning = new Map();

function tuneKey(which, nodeName) {
  return `${which}:${nodeName}`;
}

function tuningStateFor(which, nodeName) {
  const key = tuneKey(which, nodeName);
  if (!tuning.has(key)) {
    tuning.set(key, { status: "idle", log: [], result: null, error: null });
  }
  return tuning.get(key);
}

// One "Tune full graph" run per side -- drives the exact same per-node
// `tuning` map entries a click on an individual node's own button would
// (see handleTuneFullGraphClick), so every Conv node's own card updates
// live as the batch works through it, instead of duplicating a whole
// separate results display. Only tracks the batch's own overall progress;
// a node's success/failure/result lives in `tuning` as usual.
// {status: "idle"|"running"|"done", nodeNames: string[], doneCount: number}
const fullGraphTuning = new Map();

function fullGraphStateFor(which) {
  if (!fullGraphTuning.has(which)) {
    fullGraphTuning.set(which, { status: "idle", nodeNames: [], doneCount: 0 });
  }
  return fullGraphTuning.get(which);
}

// Every Conv node for a side, already-annotated ones first (display order),
// deduplicated -- tunableConvNodes is already filtered to exclude them (see
// setSide's own comment), so a plain concat is enough here.
function allConvNodeNames(side) {
  return [...side.annotations.map((a) => a.nodeName), ...side.tunableConvNodes];
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// One step's own <details> block: entry point/dispatch/bindings summary
// line, with the raw WGSL source collapsed inside (can be long).
function stepHtml(step) {
  const bindings = step.bindings.map((b) => `<code>${esc(b)}</code>`).join(", ");
  return (
    `<details class="wk-step">` +
    `<summary>step ${step.index}: <code>${esc(step.entryPoint)}</code> — ` +
    `dispatch [${step.dispatch.join(", ")}] — ${step.bindings.length} binding(s)</summary>` +
    `<div class="wk-bindings">${bindings}</div>` +
    `<pre class="wk-wgsl">${esc(step.wgsl)}</pre>` +
    `</details>`
  );
}

function tuneResultHtml(which, nodeName, t) {
  if (t.status === "idle") {
    return `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Tune this kernel…</button>`;
  }
  const log = t.log.length ? `<div class="wk-tune-log">${t.log.map((l) => esc(l)).join("<br>")}</div>` : "";
  if (t.status === "running") {
    return `<div class="wk-tune-status">Tuning…</div>${log}`;
  }
  if (t.status === "error") {
    return (
      `<div class="wk-tune-status wk-tune-error">Tuning failed: ${esc(t.error)}</div>${log}` +
      `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Try again</button>`
    );
  }
  // done
  const { results, winner } = t.result;
  const rows = results
    .map((r, i) => {
      const cls = r === winner ? "wk-tune-winner" : "";
      const gpu = r.gpuDurationNs !== null ? ` (GPU: ${(r.gpuDurationNs / 1e6).toFixed(3)}ms)` : "";
      return (
        `<tr class="${cls}"><td>${i === 0 ? "★" : ""}</td>` +
        `<td><code>${esc(r.appliedOpts)}</code></td>` +
        `<td>${r.medianMs.toFixed(3)}ms${gpu}</td></tr>`
      );
    })
    .join("");
  return (
    `${log}` +
    `<table class="wk-tune-table"><thead><tr><th></th><th>applied opts</th><th>median time</th></tr></thead>` +
    `<tbody>${rows}</tbody></table>` +
    `<button type="button" class="wk-tune-btn" data-action="export" data-which="${esc(which)}" data-node="${esc(nodeName)}">Export tuned model (winner) ↓</button> ` +
    `<button type="button" class="wk-tune-btn" data-action="tune" data-which="${esc(which)}" data-node="${esc(nodeName)}">Re-tune</button>`
  );
}

function annotationHtml(a, which) {
  const intermediateNote = a.intermediateCount
    ? ` — ${a.intermediateCount} intermediate buffer(s): ` +
      Object.entries(a.intermediates)
        .map(([name, bytes]) => `<code>${esc(name)}</code> (${bytes}B)`)
        .join(", ")
    : "";
  const t = tuningStateFor(which, a.nodeName);
  return (
    `<div class="wk-node">` +
    `<div class="wk-node-head"><code>${esc(a.nodeName)}</code> — ` +
    `${a.stepCount} step(s)${intermediateNote}</div>` +
    a.steps.map(stepHtml).join("") +
    `<div class="wk-tune">${tuneResultHtml(which, a.nodeName, t)}</div>` +
    `</div>`
  );
}

// A Conv node with no kernel spec attached yet -- just its name and the same
// tune UI an already-annotated node gets, so "Tune this kernel" is
// discoverable on a plain, never-flagged Conv node too (see setSide's own
// comment: this is the common case, not the exception).
function tunableConvNodeHtml(nodeName, which) {
  const t = tuningStateFor(which, nodeName);
  return (
    `<div class="wk-node">` +
    `<div class="wk-node-head"><code>${esc(nodeName)}</code> — no custom kernel attached yet</div>` +
    `<div class="wk-tune">${tuneResultHtml(which, nodeName, t)}</div>` +
    `</div>`
  );
}

// The single "Tune every Conv node in this model" entry point -- sits above
// the per-node lists since it's the fastest way to get a fully-tuned export
// for a model with more than a couple of Conv nodes (clicking each one's own
// button is still there for a single node, or to re-tune one node after a
// full-graph run). Not shown at all when there's nothing to tune.
function fullGraphSectionHtml(which, side) {
  const nodeNames = allConvNodeNames(side);
  if (nodeNames.length === 0) return "";
  const fg = fullGraphStateFor(which);

  if (fg.status === "idle") {
    return (
      `<div class="wk-fullgraph">` +
      `<button type="button" class="wk-tune-btn" data-action="tune-full-graph" data-which="${esc(which)}">` +
      `Tune full graph… (${nodeNames.length} Conv node${nodeNames.length === 1 ? "" : "s"})</button>` +
      `</div>`
    );
  }
  if (fg.status === "running") {
    return (
      `<div class="wk-fullgraph">` +
      `<div class="wk-tune-status">Tuning full graph… (${fg.doneCount}/${fg.nodeNames.length} node(s) done)</div>` +
      `</div>`
    );
  }
  // done -- tally each node's own (already-updated) tuning state.
  const succeeded = fg.nodeNames.filter((n) => tuningStateFor(which, n).status === "done");
  const failed = fg.nodeNames.filter((n) => tuningStateFor(which, n).status === "error");
  const summary =
    `Tuned ${succeeded.length}/${fg.nodeNames.length} node(s) successfully` +
    (failed.length ? ` — failed: ${failed.map((n) => esc(n)).join(", ")}` : "");
  return (
    `<div class="wk-fullgraph">` +
    `<div class="wk-tune-status">${summary}</div>` +
    (succeeded.length
      ? `<button type="button" class="wk-tune-btn" data-action="export-full-graph" data-which="${esc(which)}">Export full graph (${succeeded.length} winner${succeeded.length === 1 ? "" : "s"}) ↓</button> `
      : "") +
    `<button type="button" class="wk-tune-btn" data-action="tune-full-graph" data-which="${esc(which)}">Re-tune full graph</button>` +
    `</div>`
  );
}

function paneHtml(title, which, side) {
  if (!side) {
    return `<div class="wk-pane"><div class="wk-head">${esc(title)}</div><em>—</em></div>`;
  }
  const attached =
    side.annotations.length === 0
      ? `<em>no custom WebGPU kernels attached</em>`
      : side.annotations.map((a) => annotationHtml(a, which)).join("");
  const tunable = side.tunableConvNodes.length
    ? `<div class="wk-tune-section-head">Tune a Conv kernel</div>` +
      side.tunableConvNodes.map((n) => tunableConvNodeHtml(n, which)).join("")
    : "";
  return (
    `<div class="wk-pane"><div class="wk-head">${esc(title)}</div>` +
    `${fullGraphSectionHtml(which, side)}${attached}${tunable}</div>`
  );
}

function render() {
  const container = document.getElementById("webgpu-kernels-content");
  if (!container) return;
  container.innerHTML = `<div class="wk-panes">${paneHtml("Before", "before", state.before)}${paneHtml("After", "after", state.after)}</div>`;
}

// Parse model bytes (Uint8Array | ArrayBuffer) into annotations for one side
// and re-render. Never throws out to the caller -- a parse failure just
// clears that side, so a malformed model can't take the panel (or its host
// page) down.
function setSide(which, data, name) {
  try {
    const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);
    const annotations = listWebgpuKernelAnnotations(bytes);
    const alreadyAnnotated = new Set(annotations.map((a) => a.nodeName));
    // Most models never go through onnxsim.webgpu_tinygrad_codegen's own
    // gap-flagging, so `annotations` is empty for nearly every real upload --
    // the "Tune this kernel" button must not live only inside an
    // already-attached entry (see this module's own docstring for why that
    // was too narrow), so every OTHER Conv node in the graph gets offered
    // here too, deduplicated against the ones already shown above.
    let tunableConvNodes = [];
    try {
      tunableConvNodes = listConvNodeNames(bytes).filter((n) => !alreadyAnnotated.has(n));
    } catch (err) {
      console.error(`webgpu kernels (${which}) conv node listing:`, err);
    }
    state[which] = { bytes, name: name || "model.onnx", annotations, tunableConvNodes };
  } catch (err) {
    console.error(`webgpu kernels (${which}):`, err);
    state[which] = null;
  }
  // A freshly (re)loaded side starts with no tuning history of its own --
  // otherwise a stale winner from a previous file could get exported onto
  // an unrelated model that happens to share a node name.
  for (const key of [...tuning.keys()]) {
    if (key.startsWith(`${which}:`)) tuning.delete(key);
  }
  fullGraphTuning.delete(which);
  render();
}

// Lazily creates (and caches) one WebGPU device, shared by every tuning run
// on this page -- matches the pattern the webgpu_kernel_tuning*.test.mjs
// files use, requesting the timestamp-query feature when available so GPU
// durations show up alongside the wall-clock ones tuneConvKernel always
// reports.
let devicePromise = null;
function getWebgpuDevice() {
  if (!devicePromise) {
    devicePromise = (async () => {
      if (!navigator.gpu) {
        throw new Error("WebGPU is not available in this browser");
      }
      const adapter = await navigator.gpu.requestAdapter();
      if (!adapter) throw new Error("no WebGPU adapter available");
      const wantTimestamps = adapter.features.has("timestamp-query");
      return adapter.requestDevice({ requiredFeatures: wantTimestamps ? ["timestamp-query"] : [] });
    })().catch((err) => {
      devicePromise = null;
      throw err;
    });
  }
  return devicePromise;
}

async function handleTuneClick(which, nodeName) {
  const side = state[which];
  if (!side) return;
  const t = tuningStateFor(which, nodeName);
  if (t.status === "running") return;
  t.status = "running";
  t.log = [];
  t.error = null;
  t.result = null;
  render();

  try {
    const { tuneConvKernel } = await import("./webgpu_kernel_tuner.mjs");
    const device = await getWebgpuDevice();
    const result = await tuneConvKernel(device, side.bytes, nodeName, {
      onProgress: (msg) => {
        t.log.push(msg);
        render();
      },
    });
    t.status = "done";
    t.result = result;
    // Test-observability only (mirrors window.__onnxsimConverted's own
    // precedent) -- nothing reads this at runtime.
    window.__wkLastTuneResult = { which, nodeName, result };
  } catch (err) {
    console.error(`webgpu kernel tuner (${which}/${nodeName}):`, err);
    t.status = "error";
    t.error = (err && err.message) || String(err);
  }
  render();
}

function handleExportClick(which, nodeName) {
  const side = state[which];
  const t = tuningStateFor(which, nodeName);
  if (!side || t.status !== "done" || !t.result) return;
  try {
    const updated = attachWebgpuKernelSpec(side.bytes, nodeName, t.result.winner.spec);
    const base = side.name.replace(/\.onnx$/i, "");
    downloadBytes(updated, `${base}.tuned.onnx`);
  } catch (err) {
    console.error(`webgpu kernel export (${which}/${nodeName}):`, err);
    t.status = "error";
    t.error = `export failed: ${(err && err.message) || err}`;
    render();
  }
}

// Tunes every Conv node in the model, one at a time -- Pyodide/tinygrad load
// once and stay cached across nodes (webgpu_kernel_tuner.mjs's own
// module-level singleton), but each node's own dispatch loop still costs
// real GPU time, so a model with many Conv nodes can take a while; that's
// why this reports per-node progress rather than looking hung. A node that
// throws (non-static shape, more than one scheduled kernel call, ...) is
// recorded as failed in its own card and the batch moves on -- one bad node
// doesn't block tuning the rest of the graph.
async function handleTuneFullGraphClick(which) {
  const side = state[which];
  if (!side) return;
  const fg = fullGraphStateFor(which);
  if (fg.status === "running") return;

  const nodeNames = allConvNodeNames(side);
  fg.status = "running";
  fg.nodeNames = nodeNames;
  fg.doneCount = 0;
  render();

  const { tuneConvKernel } = await import("./webgpu_kernel_tuner.mjs");
  let device;
  try {
    device = await getWebgpuDevice();
  } catch (err) {
    console.error(`webgpu kernel tuner (${which}, full graph): could not get a WebGPU device:`, err);
    // No device at all -- every node fails the same way; still finish the
    // batch (rather than leaving it stuck on "running") so the summary
    // shows why.
    for (const nodeName of nodeNames) {
      const t = tuningStateFor(which, nodeName);
      t.status = "error";
      t.error = (err && err.message) || String(err);
      fg.doneCount += 1;
    }
    fg.status = "done";
    render();
    return;
  }

  for (const nodeName of nodeNames) {
    const t = tuningStateFor(which, nodeName);
    t.status = "running";
    t.log = [];
    t.error = null;
    t.result = null;
    render();

    try {
      const result = await tuneConvKernel(device, side.bytes, nodeName, {
        onProgress: (msg) => {
          t.log.push(msg);
          render();
        },
      });
      t.status = "done";
      t.result = result;
    } catch (err) {
      console.error(`webgpu kernel tuner (${which}/${nodeName}, full graph):`, err);
      t.status = "error";
      t.error = (err && err.message) || String(err);
    }
    fg.doneCount += 1;
    render();
  }

  fg.status = "done";
  // Test-observability only (mirrors window.__onnxsimConverted's own
  // precedent) -- nothing reads this at runtime.
  window.__wkLastFullGraphTuneResult = {
    which,
    nodeNames,
    results: Object.fromEntries(nodeNames.map((n) => [n, tuningStateFor(which, n)])),
  };
  render();
}

// Chains attachWebgpuKernelSpec across every node that finished tuning
// successfully -- the writer takes bytes-in/bytes-out, so folding N winners
// into one export is just N sequential calls, no new low-level machinery.
function handleExportFullGraphClick(which) {
  const side = state[which];
  const fg = fullGraphStateFor(which);
  if (!side || fg.status !== "done") return;

  let bytes = side.bytes;
  let exportedCount = 0;
  for (const nodeName of fg.nodeNames) {
    const t = tuningStateFor(which, nodeName);
    if (t.status !== "done" || !t.result) continue;
    try {
      bytes = attachWebgpuKernelSpec(bytes, nodeName, t.result.winner.spec);
      exportedCount += 1;
    } catch (err) {
      console.error(`webgpu kernel export (${which}/${nodeName}, full graph):`, err);
    }
  }
  if (exportedCount === 0) {
    console.error(`webgpu kernel export (${which}, full graph): no successfully-tuned node to export`);
    return;
  }
  const base = side.name.replace(/\.onnx$/i, "");
  downloadBytes(bytes, `${base}.tuned-full-graph.onnx`);
}

function initWebgpuKernelsPanel() {
  render(); // draw the empty placeholder up front

  const container = document.getElementById("webgpu-kernels-content");
  if (container) {
    container.addEventListener("click", (e) => {
      const btn = e.target.closest("button[data-action]");
      if (!btn) return;
      const { action, which, node } = btn.dataset;
      if (action === "tune") handleTuneClick(which, node);
      else if (action === "export") handleExportClick(which, node);
      else if (action === "tune-full-graph") handleTuneFullGraphClick(which);
      else if (action === "export-full-graph") handleExportFullGraphClick(which);
    });
  }

  const fileInput = document.getElementById("file-input");
  if (fileInput) {
    fileInput.addEventListener("change", async (e) => {
      const file = e.target.files && e.target.files[0];
      if (!file) return;
      // A new upload invalidates the previous "after" listing until the
      // conversion for this model finishes.
      state.after = null;
      try {
        setSide("before", new Uint8Array(await file.arrayBuffer()), file.name);
      } catch (err) {
        console.error("webgpu kernels (before):", err);
      }
    });
  }

  // Hugging Face downloads bypass the file input; the loader drives us here.
  window.webgpuKernelsShowBefore = (data, name) => {
    state.after = null;
    setSide("before", data, name);
  };

  // Called by the converter worker glue in index.html when a result is ready.
  window.webgpuKernelsShowAfter = (dataUrl, name) => {
    try {
      setSide("after", dataUrlToArrayBuffer(dataUrl), name);
    } catch (err) {
      console.error("webgpu kernels (after):", err);
    }
  };
}

initWebgpuKernelsPanel();
