#!/usr/bin/env python3
"""Extract real weights/scales for the ResNet-50 stem subgraph (conv7x7 -> requantize -> maxpool)
from the real `backbone.onnx` (produced by `scripts/android/maskrcnn_e2e/prepare.py`), compute
the zero-point-folded bias and requantize multiplier/shift, generate the C data files
`native_transport/`'s fused driver embeds, and verify the whole chain numerically against a real
ONNX Runtime reference sliced from the same graph. See ../README.md's "Chaining a real subgraph"
section for what this unlocked and the real bug (128-byte alignment) this pipeline's own
diagnostic run helped isolate.

Requires a prepared `backbone.onnx` + `input.npy` (real image) -- run
`scripts/android/maskrcnn_e2e/prepare.py --workdir <dir>` first, then point `--workdir` here at
the same directory.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path


def compute_folded_bias(w: "np.ndarray", bias: "np.ndarray", img_zp: int) -> "np.ndarray":
    """b' = b - img_zp * sum_{ic,kh,kw}(weight) -- folds the input activation's zero-point cross
    term into the bias, so the kernel's raw `sum(x*w)` (no explicit zero-point subtraction) plus
    this folded bias equals `sum((x-img_zp)*w) + b` exactly. Only needed for the very first conv:
    every later activation in this network has zero_point=0 (post-ReLU), a no-op to fold."""
    import numpy as np

    w_sum = w.astype(np.int64).sum(axis=(1, 2, 3))
    return (bias.astype(np.int64) - img_zp * w_sum).astype(np.int32)


def compute_multiplier_shift(double_multiplier: float) -> tuple[int, int]:
    """Same as hex_requantize_kernel.py's own (duplicated here to keep this script standalone;
    the on-device kernel itself is generated by that file, not this one)."""
    significand, exponent = math.frexp(double_multiplier)
    significand_int = round(significand * (1 << 31))
    if significand_int == (1 << 31):
        significand_int //= 2
        exponent += 1
    return significand_int, exponent


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--workdir", required=True, help="prepare.py's --workdir (has backbone.onnx, input.npy)")
    p.add_argument("--out", default=".", help="directory to write driver_*.bin data files into")
    args = p.parse_args()

    import numpy as np
    import onnx
    import onnxruntime as ort
    from onnx import numpy_helper

    workdir = Path(args.workdir)
    out = Path(args.out)
    m = onnx.load(str(workdir / "backbone.onnx"))
    g = m.graph
    inits = {i.name: numpy_helper.to_array(i) for i in g.initializer}

    # Real stem conv weight/bias/scales -- names confirmed by tracing the graph forward from the
    # `image` input (see this file's own commit message / ../README.md for the trace).
    w_i8 = inits["ConvMulFusion_W_2_quantized"].astype(np.int8)          # (64,3,7,7)
    w_scale = float(inits["ConvMulFusion_W_2_scale"])
    bias_i32 = inits["ConvAddFusion_Add_B_5_quantized"].astype(np.int32)  # (64,)
    img_scale, img_zp = float(inits["1_scale"]), int(inits["1_zero_point"])
    out_scale, out_zp = float(inits["7_scale"]), int(inits["7_zero_point"])

    folded_bias = compute_folded_bias(w_i8, bias_i32, img_zp)
    multiplier, shift = compute_multiplier_shift(img_scale * w_scale / out_scale)
    print(f"img_scale={img_scale} img_zp={img_zp} w_scale={w_scale} out_scale={out_scale} out_zp={out_zp}")
    print(f"multiplier={multiplier} shift={shift}")

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from hex_stem7x7_kernel import PAD, _round_up, pack_weight_7x7

    cin, cout = 3, 64
    cin_pad = _round_up(cin, 4)
    wp = pack_weight_7x7(w_i8, cin_pad)

    # Real image, quantized+padded the same way as the real qnn.conv2d -- the spatial border
    # uses the *real* image zero-point (114 here), not literal 0 (see hex_stem7x7_kernel.py's
    # pad_input() docstring for why literal-0 would be wrong for a real integration).
    extract_out = out / "extract_stem_maxpool.onnx"
    onnx.utils.extract_model(str(workdir / "backbone.onnx"), str(extract_out),
                              input_names=["image"], output_names=["1_2_QuantizeLinear", "9_quantized"])
    sess = ort.InferenceSession(str(extract_out), providers=["CPUExecutionProvider"])
    image = np.load(str(workdir / "input.npy")).astype(np.float32)
    quant_image, maxpool_ref = sess.run(["1_2_QuantizeLinear", "9_quantized"], {"image": image})
    quant_image = quant_image[0].transpose(1, 2, 0)  # (800,1088,3) uint8

    ih, iw, _ = quant_image.shape
    a_cpad = np.zeros((ih, iw, cin_pad), dtype=np.uint8)
    a_cpad[:, :, :cin] = quant_image
    a_pad = np.pad(a_cpad, ((PAD, PAD), (PAD, PAD), (0, 0)), mode="constant", constant_values=img_zp)
    a_pad[:, :, cin:] = 0

    wp.tofile(out / "driver_weight_packed.bin")
    folded_bias.tofile(out / "driver_bias_folded.bin")
    a_pad.tofile(out / "driver_image_padded.bin")
    np.save(out / "driver_maxpool_ref.npy", maxpool_ref[0])
    print(f"wrote weight ({wp.nbytes}B), bias ({folded_bias.nbytes}B), padded image ({a_pad.nbytes}B), "
          f"ORT reference ({maxpool_ref.nbytes}B) to {out}")


if __name__ == "__main__":
    main()
