/* SmolLM2-135M, one decode step per FastRPC call, the whole model on the CDSP (decode_ref.py is the numpy twin).
 *
 * Every Linear is a W8A8 GEMV generated by our tinygrad HVX codegen (llm_kernels.py: llm_b576_tcp / llm_b1536_tcp,
 * one 32-column block of the packed layout Wp[N/32][K/4][32][4], vrmpybusv u8 x s8 -> s32). The per-token activation
 * is quantized to uint8 (asymmetric) -- or, with a16, to a 16-bit code run as two uint8 passes (hi, lo bytes) over
 * the same weights. RMSNorm, RoPE, attention over the valid KV positions, SwiGLU and the residuals are scalar fp32.
 * Weights (int8, packed), scales/norms/RoPE tables (fp32) and the KV cache live in the DSP heap for the session.
 *
 * nthreads workers (each holding an HVX context, 256 KB stacks: tinygrad's kernels crash on small stacks) split
 * every GEMV by blocks and the attention by heads; worker 0 does the serial parts between qurt barriers. */
#include <stdlib.h>
#include <string.h>
#include "decode_rpc.h"
#include "qurt.h"
#include "HAP_power.h"
#include "hexagon_types.h"
#include "hexagon_protos.h"
#include "kernels.h"

extern unsigned long long HAP_perf_get_time_us(void);

#define H 576
#define L 30
#define NH 9
#define NKV 3
#define HD 64
#define FF 1536
#define V 49152
#define MAXLEN 256
#define QKV (H + 2 * NKV * HD)
#define MAXT 4
#define STK (256 * 1024)
/* per-layer fp32 block: ln1, ln2, then (scale, colsum) for qkv, o, gu, down */
#define FL (2 * H + 2 * QKV + 2 * H + 2 * 2 * FF + 2 * H)

static signed char* Wb;
static float* Fb;
static void *Wraw, *Fraw;
static int a16, nthr = 1, blk4, vec, vflags; /* vflags (debug bisect): 1 vrmsnorm, 2 vminmax, 4 vquant */
static float *kc, *vc, *kt; /* kt: K cache transposed [L][NKV][HD][MAXLEN] for the vector QK */
static unsigned char* stacks[MAXT];

typedef struct {
  const signed char* w;
  const float *s, *cs;
  int K, N;
  int* csi; /* colsum as int32, for the exact vector zero-point correction */
} lin_t;
static lin_t lin[L][4], head;
static const float *ln1[L], *ln2[L], *fnorm, *rcos, *rsin;

static void* amalloc(size_t n, void** raw) {
  *raw = malloc(n + 256);
  return *raw ? (void*)(((uintptr_t)*raw + 127) & ~(uintptr_t)127) : 0;
}

AEEResult decode_rpc_alloc(remote_handle64 h, int32 wbytes, int32 fbytes) {
  free(Wraw); free(Fraw);
  Wb = amalloc(wbytes, &Wraw);
  Fb = amalloc(fbytes, &Fraw);
  return Wb && Fb ? 0 : AEE_ENOMEMORY;
}

AEEResult decode_rpc_load(remote_handle64 h, int32 part, int32 off, const unsigned char* d, int n) {
  memcpy((part ? (unsigned char*)Fb : (unsigned char*)Wb) + off, d, n);
  return 0;
}

static int vote(void* ctx, int turbo) {
  HAP_power_request_t req = {0};
  req.type = HAP_power_set_HVX;
  req.hvx.power_up = 1;
  int r1 = HAP_power_set(ctx, &req);
  HAP_power_request_t d = {0};
  d.type = HAP_power_set_DCVS_v2;
  d.dcvs_v2.dcvs_enable = turbo ? FALSE : TRUE;
  d.dcvs_v2.dcvs_option = HAP_DCVS_V2_PERFORMANCE_MODE;
  d.dcvs_v2.set_latency = TRUE;
  d.dcvs_v2.latency = 40;
  d.dcvs_v2.set_dcvs_params = turbo ? TRUE : FALSE;
  d.dcvs_v2.dcvs_params.target_corner = HAP_DCVS_VCORNER_TURBO;
  d.dcvs_v2.dcvs_params.min_corner = HAP_DCVS_VCORNER_TURBO;
  d.dcvs_v2.dcvs_params.max_corner = HAP_DCVS_VCORNER_TURBO;
  int r2 = HAP_power_set(ctx, &d);
  return r1 ? r1 : r2;
}

static int* int_cs(const float* cs, int N) {
  void* raw;
  int* o = amalloc(sizeof(int) * N, &raw);
  if (o) for (int n = 0; n < N; n++) o[n] = (int)cs[n];
  return o;
}

AEEResult decode_rpc_setup(remote_handle64 h, int32 is_a16, int32 nt, int32 b4, int32 v, int32 turbo, int32* rc) {
  if (nt < 1 || nt > MAXT) return AEE_EBADPARM;
  a16 = is_a16; nthr = nt; blk4 = b4; vec = v && !is_a16; vflags = v > 1 ? v >> 1 : 7;
  static void *kraw, *vraw, *traw;
  if (!kc) {
    kc = amalloc(sizeof(float) * L * NKV * MAXLEN * HD, &kraw);
    vc = amalloc(sizeof(float) * L * NKV * MAXLEN * HD, &vraw);
    kt = amalloc(sizeof(float) * L * NKV * MAXLEN * HD, &traw);
  }
  for (int t = 0; t < MAXT; t++) if (!stacks[t]) stacks[t] = malloc(STK + 128);
  if (!kc || !vc || !stacks[MAXT - 1]) return AEE_ENOMEMORY;
  const signed char* w = Wb;
  const float* f = Fb;
  static const int KN[4][2] = {{H, QKV}, {H, H}, {H, 2 * FF}, {FF, H}};
  for (int i = 0; i < L; i++) {
    ln1[i] = f; ln2[i] = f + H;
    const float* p = f + 2 * H;
    for (int j = 0; j < 4; j++) {
      int K = KN[j][0], N = KN[j][1];
      lin[i][j] = (lin_t){w, p, p + N, K, N, lin[i][j].csi ? lin[i][j].csi : int_cs(p + N, N)};
      p += 2 * N;
      w += (size_t)K * N;
    }
    f += FL;
  }
  fnorm = f; f += H;
  head = (lin_t){w, f, f + V, H, V, head.csi ? head.csi : int_cs(f + V, V)};
  f += 2 * V;
  rcos = f; rsin = f + MAXLEN * HD / 2;
  *rc = vote((void*)(uintptr_t)h, turbo);
  return 0;
}

int decode_rpc_open(const char* uri, remote_handle64* h) { *h = (remote_handle64)(uintptr_t)malloc(1); return *h ? 0 : -1; }
int decode_rpc_close(remote_handle64 h) { if (h) free((void*)(uintptr_t)h); return 0; }

/* ---- scalar fp32 helpers (no libm in the skel) ---- */
static inline float fexp(float x) {
  if (x < -87.f) return 0.f;
  if (x > 88.f) x = 88.f;
  float t = x * 1.44269504089f;
  int i = (int)t;
  if ((float)i > t) i--;
  float r = t - (float)i;
  float p = 1.f + r * (0.693147181f + r * (0.240226507f + r * (0.0555041087f + r * (0.00961812911f + r * (0.00133335581f + r * 0.000154035304f)))));
  union { float f; int i; } u;
  u.i = (i + 127) << 23;
  return u.f * p;
}
static inline double rsqrt_d(double v) {
  union { float f; int i; } u;
  u.f = (float)v;
  u.i = 0x5f3759df - (u.i >> 1);
  double y = u.f;
  for (int k = 0; k < 4; k++) y = y * (1.5 - 0.5 * v * y * y);
  return y;
}
static void rmsnorm(float* o, const float* x, const float* g) {
  float ss = 0.f;
  for (int i = 0; i < H; i++) ss += x[i] * x[i];
  float r = (float)rsqrt_d(ss / H + 1e-5);
  for (int i = 0; i < H; i++) o[i] = x[i] * r * g[i];
}

/* shared per-token state */
static unsigned char xq[2][FF] __attribute__((aligned(128))); /* [0]: u8 code (a8) or hi byte (a16), [1]: lo byte */
static float xs;
static int xzp;
static int acc[2][2 * FF] __attribute__((aligned(128)));
static int hacc[2][V] __attribute__((aligned(128)));
static float hbuf[H] __attribute__((aligned(128))), nbuf[H] __attribute__((aligned(128))), ybuf[2 * FF] __attribute__((aligned(128))),
    att[H] __attribute__((aligned(128))), gbuf[FF] __attribute__((aligned(128))), *logits_out;
static float tmin[MAXT], tmax[MAXT];
static int cur_pos;
static qurt_barrier_t bar;
static unsigned long long gemv_t, prof_t[8];
#define TIC(k) unsigned long long tk##k = HAP_perf_get_time_us()
#define TOC(k, slot) do { if (!tid) prof_t[slot] += HAP_perf_get_time_us() - tk##k; } while (0)

static void quantize(const float* x, int n, float lo, float hi) {
  if (lo > 0.f) lo = 0.f;
  if (hi < 0.f) hi = 0.f;
  float levels = a16 ? 65535.f : 255.f;
  float s = (hi - lo) / levels;
  if (s < 1e-12f) s = 1e-12f;
  int zpi = (int)(-lo / s + 0.5f);
  float zp = (float)zpi, inv = 1.f / s;
  for (int i = 0; i < n; i++) {
    float t = x[i] * inv + zp;
    t = t < 0.f ? 0.f : (t > levels ? levels : t);
    int q = (int)(t + 0.5f);
    if (a16) { xq[0][i] = (unsigned char)(q >> 8); xq[1][i] = (unsigned char)q; }
    else xq[0][i] = (unsigned char)q;
  }
  xs = s; xzp = zpi;
}
static void quant_minmax(const float* x, int n) {
  float lo = x[0], hi = x[0];
  for (int i = 1; i < n; i++) { lo = x[i] < lo ? x[i] : lo; hi = x[i] > hi ? x[i] : hi; }
  quantize(x, n, lo, hi);
}

static void gemv_blocks(const lin_t* l, int* out, int tid, int ldo) {
  int nb = l->N / 32, step = blk4 ? 4 : 1;
  int ngroups = (nb + step - 1) / step;
  for (int g = tid; g < ngroups; g += nthr) {
    int b = g * step;
    for (int pass = 0; pass < (a16 ? 2 : 1); pass++) {
      int* o = out + (size_t)pass * ldo + b * 32;
      const signed char* w = l->w + (size_t)b * 32 * l->K;
      if (step == 4 && b + 4 <= nb) {
        if (l->K == H) llm_b576x4_tcp(o, xq[pass], (signed char*)w);
        else llm_b1536x4_tcp(o, xq[pass], (signed char*)w);
      } else {
        for (int bb = b; bb < b + step && bb < nb; bb++) {
          int* ob = out + (size_t)pass * ldo + bb * 32;
          const signed char* wb = l->w + (size_t)bb * 32 * l->K;
          if (l->K == H) llm_b576_tcp(ob, xq[pass], (signed char*)wb);
          else llm_b1536_tcp(ob, xq[pass], (signed char*)wb);
        }
      }
    }
  }
}
/* exact integer zero-point correction (int32 for a8: |zp*colsum| <= 255*127*1536; int64 for a16), then one fp32
   scale: the scalar core's double-precision math is slow, so no double here */
static inline float deq(const lin_t* l, const int* a0, const int* a1, int n) {
  int cs = (int)l->cs[n];
  if (a16) return (float)((long long)a0[n] * 256 + a1[n] - (long long)xzp * cs) * (xs * l->s[n]);
  return (float)(a0[n] - xzp * cs) * (xs * l->s[n]);
}
/* ---- HVX qf32 (V69 has no IEEE vector float: multiply/add in qf32, convert back to IEEE sf) ---- */
static inline int fbits(float f) { int i; memcpy(&i, &f, 4); return i; }
#define SPLATF(f) Q6_V_vsplat_R(fbits(f))
#define SF(q) Q6_Vsf_equals_Vqf32(q)
#define VMUL(a, b) SF(Q6_Vqf32_vmpy_VsfVsf((a), (b)))
#define VADD(a, b) SF(Q6_Vqf32_vadd_VsfVsf((a), (b)))
#define VSUB(a, b) SF(Q6_Vqf32_vsub_VsfVsf((a), (b)))
/* exact int32 -> fp32 (rounded once): hi/lo 16-bit halves each through the 1.5*2^23 magic number */
static inline HVX_Vector vcvt_w_sf(HVX_Vector d) {
  const HVX_Vector mi = Q6_V_vsplat_R(0x4B400000), mf = SPLATF(12582912.0f);
  HVX_Vector hi = Q6_Vw_vasr_VwR(d, 16), lo = Q6_V_vand_VV(d, Q6_V_vsplat_R(0xFFFF));
  HVX_Vector fhi = VSUB(Q6_Vw_vadd_VwVw(hi, mi), mf), flo = VSUB(Q6_Vw_vadd_VwVw(lo, mi), mf);
  return SF(Q6_Vqf32_vadd_Vqf32Vsf(Q6_Vqf32_vmpy_VsfVsf(fhi, SPLATF(65536.0f)), flo));
}
/* 32 dequantized outputs n..n+31: (acc - zp*colsum) exactly in int32, then * (xs * s[n]) */
static inline HVX_Vector deq32(const lin_t* l, const int* a, int n) {
  HVX_Vector zp = Q6_V_vsplat_R(xzp | (xzp << 16));
  HVX_Vector d = Q6_Vw_vsub_VwVw(*(const HVX_Vector*)(a + n), Q6_Vw_vmpyie_VwVuh(*(const HVX_Vector*)(l->csi + n), zp));
  return VMUL(vcvt_w_sf(d), VMUL(*(const HVX_Vector*)(l->s + n), SPLATF(xs)));
}
/* e^x for x in [-126 ln2, 126 ln2] (clamped): 2^round(t) * poly(t - round(t)), t = x log2 e */
static inline HVX_Vector vexp(HVX_Vector x) {
  HVX_Vector t = VMUL(x, SPLATF(1.44269504089f));
  HVX_Vector ab = Q6_V_vand_VV(t, Q6_V_vsplat_R(0x7FFFFFFF)), b126 = Q6_V_vsplat_R(fbits(126.f));
  t = Q6_V_vmux_QVV(Q6_Q_vcmp_gt_VwVw(ab, b126), Q6_V_vor_VV(b126, Q6_V_vand_VV(t, Q6_V_vsplat_R(0x80000000))), t);
  HVX_Vector ti = VADD(t, SPLATF(12582912.0f));            /* bits = 0x4B400000 + round(t) */
  HVX_Vector i = Q6_Vw_vsub_VwVw(ti, Q6_V_vsplat_R(0x4B400000));
  HVX_Vector r = VSUB(t, VSUB(ti, SPLATF(12582912.0f)));    /* t - round(t) in [-0.5, 0.5] */
  static const float c[] = {0.000154035304f, 0.00133335581f, 0.00961812911f, 0.0555041087f, 0.240226507f, 0.693147181f, 1.f};
  HVX_Vector p = SPLATF(c[0]);
  for (int k = 1; k < 7; k++) p = SF(Q6_Vqf32_vadd_Vqf32Vsf(Q6_Vqf32_vmpy_VsfVsf(p, r), SPLATF(c[k])));
  HVX_Vector sc = Q6_Vw_vasl_VwR(Q6_Vw_vadd_VwVw(i, Q6_V_vsplat_R(127)), 23);
  return VMUL(p, sc);
}
/* 1/x for x >= 1 (bit-trick seed + 3 Newton steps) */
static inline HVX_Vector vrecip(HVX_Vector x) {
  HVX_Vector y = Q6_Vw_vsub_VwVw(Q6_V_vsplat_R(0x7EF311C7), x), two = SPLATF(2.f);
  for (int k = 0; k < 3; k++) y = VMUL(y, VSUB(two, VMUL(x, y)));
  return y;
}
/* float min/max through order-preserving int keys: k = bits ^ ((bits >> 31) & 0x7FFFFFFF) */
static inline HVX_Vector fkey(HVX_Vector v) { return Q6_V_vxor_VV(v, Q6_V_vand_VV(Q6_Vw_vasr_VwR(v, 31), Q6_V_vsplat_R(0x7FFFFFFF))); }
static inline float keyf(int k) { int b = k ^ ((k >> 31) & 0x7FFFFFFF); float f; memcpy(&f, &b, 4); return f; }
static void vminmax(const float* x, int n, float* lo, float* hi) {
  if (!(vflags & 2)) {
    float a = x[0], z = x[0];
    for (int i = 1; i < n; i++) { a = x[i] < a ? x[i] : a; z = x[i] > z ? x[i] : z; }
    *lo = a; *hi = z;
    return;
  }
  HVX_Vector mn = fkey(*(const HVX_Vector*)x), mx = mn;
  for (int b = 1; b < n / 32; b++) { HVX_Vector k = fkey(((const HVX_Vector*)x)[b]); mn = Q6_Vw_vmin_VwVw(mn, k); mx = Q6_Vw_vmax_VwVw(mx, k); }
  int t[64] __attribute__((aligned(128)));
  ((HVX_Vector*)t)[0] = mn; ((HVX_Vector*)t)[1] = mx;
  int a = t[0], z = t[32];
  for (int k = 1; k < 32; k++) { a = t[k] < a ? t[k] : a; z = t[32 + k] > z ? t[32 + k] : z; }
  *lo = keyf(a); *hi = keyf(z);
}
/* floor(x / s + zp + 0.5) clamped to [0, 255] (= the scalar path's rounding), 32 lanes at a time; bytes stored
   scalar. The qf32 -> sf conversion behind the 1.5*2^23 magic number does not round to nearest (a bias of up to one
   step on every activation broke accuracy), so the magic integer is corrected to the floor with the exact fraction. */
static void vquant(const float* x, int n, float inv, int zp) {
  const HVX_Vector vinv = SPLATF(inv), off = SPLATF((float)zp + 0.5f), mf = SPLATF(12582912.0f), mi = Q6_V_vsplat_R(0x4B400000);
  const HVX_Vector z = Q6_V_vzero(), c255 = Q6_V_vsplat_R(255), m1 = Q6_V_vsplat_R(-1);
  int t[32] __attribute__((aligned(128)));
  for (int b = 0; b < n / 32; b++) {
    HVX_Vector y = SF(Q6_Vqf32_vadd_Vqf32Vsf(Q6_Vqf32_vmpy_VsfVsf(((const HVX_Vector*)x)[b], vinv), off));
    HVX_Vector ti = VADD(y, mf);
    HVX_Vector q = Q6_Vw_vsub_VwVw(ti, mi);
    HVX_Vector frac = VSUB(y, VSUB(ti, mf)); /* y - float(q), exact */
    q = Q6_Vw_vadd_VwVw(q, Q6_V_vmux_QVV(Q6_Q_vcmp_gt_VwVw(z, frac), m1, z));
    *(HVX_Vector*)t = Q6_Vw_vmin_VwVw(Q6_Vw_vmax_VwVw(q, z), c255);
    for (int k = 0; k < 32; k++) xq[0][b * 32 + k] = (unsigned char)t[k];
  }
}
static void vrmsnorm(float* o, const float* x, const float* g) {
  HVX_Vector a = Q6_V_vzero();
  for (int b = 0; b < H / 32; b++) a = Q6_Vqf32_vadd_Vqf32Vqf32(a, Q6_Vqf32_vmpy_VsfVsf(((const HVX_Vector*)x)[b], ((const HVX_Vector*)x)[b]));
  float t[32] __attribute__((aligned(128)));
  *(HVX_Vector*)t = SF(a);
  float ss = 0.f;
  for (int k = 0; k < 32; k++) ss += t[k];
  HVX_Vector r = SPLATF((float)rsqrt_d(ss / H + 1e-5));
  for (int b = 0; b < H / 32; b++) ((HVX_Vector*)o)[b] = VMUL(VMUL(((const HVX_Vector*)x)[b], r), ((const HVX_Vector*)g)[b]);
}
static void vquant_mm(const float* x, int n, float lo, float hi) {
  if (!(vflags & 4)) { quantize(x, n, lo, hi); return; }
  if (lo > 0.f) lo = 0.f;
  if (hi < 0.f) hi = 0.f;
  float s = (hi - lo) / 255.f;
  if (s < 1e-12f) s = 1e-12f;
  int zp = (int)(-lo / s + 0.5f);
  vquant(x, n, 1.f / s, zp);
  xs = s; xzp = zp;
}
static void norm_quant(const float* x, const float* g) {
  if (!vec) { rmsnorm(nbuf, x, g); quant_minmax(nbuf, H); return; }
  float lo, hi;
  if (vflags & 1) vrmsnorm(nbuf, x, g);
  else rmsnorm(nbuf, x, g);
  vminmax(nbuf, H, &lo, &hi);
  vquant_mm(nbuf, H, lo, hi);
}
static float hmaxf(HVX_Vector v) { float t[32] __attribute__((aligned(128))); *(HVX_Vector*)t = v; float m = t[0]; for (int k = 1; k < 32; k++) m = t[k] > m ? t[k] : m; return m; }

#define SYNC() qurt_barrier_wait(&bar)
#define GEMV(l, out, ld)                                          \
  do {                                                            \
    unsigned long long t0_ = HAP_perf_get_time_us();              \
    gemv_blocks(l, out, tid, ld);                                 \
    SYNC();                                                       \
    if (!tid) gemv_t += HAP_perf_get_time_us() - t0_;             \
  } while (0)

static void worker(void* arg) {
  int tid = (int)(uintptr_t)arg, pos = cur_pos;
  qurt_hvx_lock(QURT_HVX_MODE_128B);
  const float *c = rcos + pos * HD / 2, *s = rsin + pos * HD / 2;
  for (int i = 0; i < L; i++) {
    TIC(a);
    if (!tid) norm_quant(hbuf, ln1[i]);
    SYNC();
    TOC(a, 0);
    GEMV(&lin[i][0], acc[0], 2 * FF);
    TIC(b);
    /* q/k/v dequant + RoPE; k, v appended to the cache (all threads: disjoint rows) */
    if (vec) for (int r = tid; r < NH + 2 * NKV; r += nthr) {
      HVX_Vector a = deq32(&lin[i][0], acc[0], r * HD), b = deq32(&lin[i][0], acc[0], r * HD + 32);
      if (r < NH + NKV) {
        HVX_Vector cc = *(const HVX_Vector*)c, ss = *(const HVX_Vector*)s;
        HVX_Vector ra = VSUB(VMUL(a, cc), VMUL(b, ss)), rb = VADD(VMUL(b, cc), VMUL(a, ss));
        if (r < NH) { ((HVX_Vector*)(ybuf + r * HD))[0] = ra; ((HVX_Vector*)(ybuf + r * HD))[1] = rb; }
        else {
          float t[HD] __attribute__((aligned(128)));
          ((HVX_Vector*)t)[0] = ra; ((HVX_Vector*)t)[1] = rb;
          float* kd = kt + (size_t)(i * NKV + r - NH) * HD * MAXLEN + pos;
          for (int d = 0; d < HD; d++) kd[d * MAXLEN] = t[d];
        }
      } else {
        HVX_Vector* vd = (HVX_Vector*)(vc + ((size_t)(i * NKV + r - NH - NKV) * MAXLEN + pos) * HD);
        vd[0] = a; vd[1] = b;
      }
    }
    else for (int r = tid; r < NH + 2 * NKV; r += nthr) {
      float v64[HD];
      for (int d = 0; d < HD; d++) v64[d] = deq(&lin[i][0], acc[0], acc[1], r * HD + d);
      float* dst = r < NH ? ybuf + r * HD : (r < NH + NKV ? kc + ((size_t)(i * NKV + r - NH) * MAXLEN + pos) * HD
                                                          : vc + ((size_t)(i * NKV + r - NH - NKV) * MAXLEN + pos) * HD);
      if (r < NH + NKV)
        for (int d = 0; d < HD / 2; d++) {
          float a = v64[d], b = v64[d + HD / 2];
          dst[d] = a * c[d] - b * s[d];
          dst[d + HD / 2] = b * c[d] + a * s[d];
        }
      else memcpy(dst, v64, sizeof v64);
    }
    SYNC();
    TOC(b, 1);
    TIC(c);
    if (vec) for (int hh = tid; hh < NH; hh += nthr) {
      /* scores for 32 positions per vector: sum_d q[d] * Kt[d][p..p+31]; softmax with vector exp; PV per position */
      int kv = hh / (NH / NKV), np = (pos + 32) / 32;
      const float* q = ybuf + hh * HD;
      const float* Kt = kt + (size_t)(i * NKV + kv) * HD * MAXLEN;
      const float* Vv = vc + (size_t)(i * NKV + kv) * MAXLEN * HD;
      float sc[MAXLEN] __attribute__((aligned(128)));
      float mx = -1e30f;
      for (int b = 0; b < np; b++) {
        HVX_Vector a = Q6_Vqf32_vmpy_VsfVsf(*(const HVX_Vector*)(Kt + b * 32), SPLATF(q[0] * 0.125f));
        for (int d = 1; d < HD; d++)
          a = Q6_Vqf32_vadd_Vqf32Vqf32(a, Q6_Vqf32_vmpy_VsfVsf(*(const HVX_Vector*)(Kt + d * MAXLEN + b * 32), SPLATF(q[d] * 0.125f)));
        ((HVX_Vector*)sc)[b] = SF(a);
      }
      for (int p = 0; p <= pos; p++) mx = sc[p] > mx ? sc[p] : mx;
      float sum = 0.f;
      for (int b = 0; b < np; b++) ((HVX_Vector*)sc)[b] = vexp(VSUB(((HVX_Vector*)sc)[b], SPLATF(mx)));
      for (int p = 0; p <= pos; p++) sum += sc[p];
      float inv = 1.f / sum;
      HVX_Vector o0 = Q6_V_vzero(), o1 = Q6_V_vzero(); /* qf32 zero */
      for (int p = 0; p <= pos; p++) {
        HVX_Vector w = SPLATF(sc[p] * inv);
        o0 = Q6_Vqf32_vadd_Vqf32Vqf32(o0, Q6_Vqf32_vmpy_VsfVsf(((const HVX_Vector*)(Vv + p * HD))[0], w));
        o1 = Q6_Vqf32_vadd_Vqf32Vqf32(o1, Q6_Vqf32_vmpy_VsfVsf(((const HVX_Vector*)(Vv + p * HD))[1], w));
      }
      ((HVX_Vector*)(att + hh * HD))[0] = SF(o0);
      ((HVX_Vector*)(att + hh * HD))[1] = SF(o1);
    }
    else for (int hh = tid; hh < NH; hh += nthr) {
      int kv = hh / (NH / NKV);
      const float* q = ybuf + hh * HD;
      const float* K = kc + (size_t)(i * NKV + kv) * MAXLEN * HD;
      const float* Vv = vc + (size_t)(i * NKV + kv) * MAXLEN * HD;
      float sc[MAXLEN], mx = -1e30f, sum = 0.f;
      for (int p = 0; p <= pos; p++) {
        float d = 0.f;
        for (int e = 0; e < HD; e++) d += q[e] * K[p * HD + e];
        sc[p] = d * 0.125f;
        mx = sc[p] > mx ? sc[p] : mx;
      }
      for (int p = 0; p <= pos; p++) { sc[p] = fexp(sc[p] - mx); sum += sc[p]; }
      float* o = att + hh * HD;
      for (int e = 0; e < HD; e++) o[e] = 0.f;
      for (int p = 0; p <= pos; p++) {
        float w = sc[p] / sum;
        for (int e = 0; e < HD; e++) o[e] += w * Vv[p * HD + e];
      }
    }
    SYNC();
    TOC(c, 2);
    TIC(d);
    if (!tid) {
      if (vec) { float lo, hi; vminmax(att, H, &lo, &hi); vquant_mm(att, H, lo, hi); }
      else quant_minmax(att, H);
    }
    SYNC();
    TOC(d, 3);
    GEMV(&lin[i][1], acc[0], 2 * FF);
    TIC(e);
    if (vec) {
      for (int b = tid; b < H / 32; b += nthr) ((HVX_Vector*)hbuf)[b] = VADD(((HVX_Vector*)hbuf)[b], deq32(&lin[i][1], acc[0], b * 32));
      SYNC();
    }
    if (!tid) {
      if (!vec) for (int n = 0; n < H; n++) hbuf[n] += deq(&lin[i][1], acc[0], acc[1], n);
      norm_quant(hbuf, ln2[i]);
    }
    SYNC();
    TOC(e, 4);
    GEMV(&lin[i][2], acc[0], 2 * FF);
    TIC(f);
    if (vec) { /* SwiGLU, 32 per vector: g * u / (1 + e^-g) */
      float lo = 1e30f, hi = -1e30f;
      for (int b = tid; b < FF / 32; b += nthr) {
        HVX_Vector g = deq32(&lin[i][2], acc[0], b * 32), u = deq32(&lin[i][2], acc[0], FF + b * 32);
        HVX_Vector e = vexp(Q6_V_vxor_VV(g, Q6_V_vsplat_R(0x80000000)));
        HVX_Vector y = VMUL(VMUL(g, u), vrecip(VADD(e, SPLATF(1.f))));
        ((HVX_Vector*)gbuf)[b] = y;
      }
      (void)lo; (void)hi;
    } else { /* SwiGLU over a slice per thread, local min/max */
      int n0 = FF * tid / nthr, n1 = FF * (tid + 1) / nthr;
      float lo = 1e30f, hi = -1e30f;
      for (int n = n0; n < n1; n++) {
        float g = deq(&lin[i][2], acc[0], acc[1], n), u = deq(&lin[i][2], acc[0], acc[1], FF + n);
        float y = g / (1.f + fexp(-g)) * u;
        gbuf[n] = y;
        lo = y < lo ? y : lo; hi = y > hi ? y : hi;
      }
      tmin[tid] = lo; tmax[tid] = hi;
    }
    SYNC();
    if (!tid) {
      float lo = tmin[0], hi = tmax[0];
      if (vec) { vminmax(gbuf, FF, &lo, &hi); vquant_mm(gbuf, FF, lo, hi); }
      else {
        for (int t = 1; t < nthr; t++) { lo = tmin[t] < lo ? tmin[t] : lo; hi = tmax[t] > hi ? tmax[t] : hi; }
        quantize(gbuf, FF, lo, hi);
      }
    }
    SYNC();
    TOC(f, 5);
    GEMV(&lin[i][3], acc[0], 2 * FF);
    TIC(g);
    if (vec) for (int b = tid; b < H / 32; b += nthr) ((HVX_Vector*)hbuf)[b] = VADD(((HVX_Vector*)hbuf)[b], deq32(&lin[i][3], acc[0], b * 32));
    else if (!tid) for (int n = 0; n < H; n++) hbuf[n] += deq(&lin[i][3], acc[0], acc[1], n);
    SYNC();
    TOC(g, 4);
  }
  TIC(h);
  if (!tid) norm_quant(hbuf, fnorm);
  SYNC();
  GEMV(&head, hacc[0], V);
  if (vec) {
    float tmp[32] __attribute__((aligned(128)));
    int al = !((uintptr_t)logits_out & 127);
    for (int b = tid; b < V / 32; b += nthr) {
      if (al) ((HVX_Vector*)logits_out)[b] = deq32(&head, hacc[0], b * 32);
      else { *(HVX_Vector*)tmp = deq32(&head, hacc[0], b * 32); memcpy(logits_out + b * 32, tmp, sizeof tmp); }
    }
  } else
    for (int n = V * tid / nthr; n < V * (tid + 1) / nthr; n++) logits_out[n] = deq(&head, hacc[0], hacc[1], n);
  TOC(h, 6);
  qurt_hvx_unlock();
  qurt_thread_exit(0);
}

AEEResult decode_rpc_step(remote_handle64 h, int32 pos, const float* emb, int embLen, float* logits, int logitsLen,
                          uint64* dsp_us, uint64* gemv_us, uint64* prof, int profLen) {
  if (pos < 0 || pos >= MAXLEN || embLen != H || logitsLen != V || !Wb) return AEE_EBADPARM;
  unsigned long long t0 = HAP_perf_get_time_us();
  memcpy(hbuf, emb, sizeof hbuf);
  logits_out = logits;
  cur_pos = pos;
  gemv_t = 0;
  memset(prof_t, 0, sizeof prof_t);
  qurt_barrier_init(&bar, nthr);
  qurt_thread_t tids[MAXT];
  for (int t = 0; t < nthr; t++) {
    qurt_thread_attr_t attr;
    qurt_thread_attr_init(&attr);
    qurt_thread_attr_set_name(&attr, "dec");
    qurt_thread_attr_set_stack_addr(&attr, (void*)(((uintptr_t)stacks[t] + 127) & ~(uintptr_t)127));
    qurt_thread_attr_set_stack_size(&attr, STK);
    /* same priority as the RPC thread (a higher-priority helper was one of the HMX probe's hang suspects) */
    qurt_thread_attr_set_priority(&attr, qurt_thread_get_priority(qurt_thread_get_id()));
    if (qurt_thread_create(&tids[t], &attr, worker, (void*)(uintptr_t)t) != QURT_EOK) return AEE_EFAILED;
  }
  for (int t = 0; t < nthr; t++) { int st; qurt_thread_join(tids[t], &st); }
  qurt_barrier_destroy(&bar);
  *dsp_us = HAP_perf_get_time_us() - t0;
  *gemv_us = gemv_t;
  for (int k = 0; k < profLen && k < 8; k++) prof[k] = prof_t[k];
  unsigned long long spawn = 0; (void)spawn;
  return 0;
}
