#!/usr/bin/env python3
"""SmolLM2-135M's decode-step GEMVs written as plain tinygrad Tensor code, generated by our tinygrad
HVX codegen, checked exact against numpy under qemu (DEV=DSP MOCKDSP=1), and emitted as C for the
phone skel (llm_rpc).

  PYTHONPATH=<onnxsim/tinygrad checkout> CC=clang-19 python llm_kernels.py --out DIR

Decode is a W8A8 GEMV per Linear: x uint8 [1,K] (one token's activation) times W int8 [K,N] with
int32 accumulation -- exactly vrmpybusv's u8 x s8 -> s32 dot4. Two SmolLM2 shapes cover every layer:

  up   : K=576,  N=1536  (gate_proj/up_proj; q/k/v/o are the same K with smaller N)
  down : K=1536, N=576   (down_proj)

Per op, two versions of the same Tensor expression:
  tc     : x.matmul(W, dtype=int32) -- the u8 x s8 inputs let tinygrad use the vrmpy TensorCore
  int32  : x.cast(int32) @ W.cast(int32) -- widened first, so plain HVX int32 multiply-adds
Writes DIR/kernels.h (llm_<op>_<variant>(out, x, w)) and DIR/<op>_{x,w,ref}.bin.
"""

import argparse
import os
import re
import sys

os.environ.setdefault("DEV", "DSP")
os.environ.setdefault("MOCKDSP", "1")
import numpy as np
from tinygrad import Tensor, dtypes
from tinygrad.helpers import Context
from tinygrad.renderer.cstyle import ClangRenderer

SHAPES = {
    "up": (576, 1536),
    "down": (1536, 576),
    "qo": (576, 576),
    "kv": (576, 192),
    # one / four 32-column blocks of the packed layout: the whole-model decode (decode_impl.c) calls these per
    # block range, so one kernel per K serves every Linear of that K and any split across HVX threads
    "b576": (576, 32),
    "b1536": (1536, 32),
    "b576x4": (576, 128),
    "b1536x4": (1536, 128),
}
# row-major variants (tc, int32) only for up/down: they are the slow bytewise-gather path, kept as the before/after reference
PACKED_ONLY = {"qo", "kv", "b576", "b1536", "b576x4", "b1536x4"}

captured: list[str] = []
_orig = ClangRenderer.render


def _capture(self, uops):
    src = _orig(self, uops)
    captured.append(src)
    return src


ClangRenderer.render = _capture


def kernel_c(src: str, new_name: str):
    """Split one rendered kernel into (typedefs, static-inline helpers, the kernel function renamed).

    tinygrad's vector typedef names (int32 = int x32, int64, ...) clash with the Hexagon SDK's scalar
    int32/int64 (AEEStdDef.h), so every typedef'd name gets a tg_ prefix. Helpers (the vrmpy WMMA
    wrapper) are returned separately so kernels.h defines each one once."""
    body = src.split("/* DSP boilerplate */")[0]
    typedefs = [ln for ln in body.splitlines() if ln.startswith("typedef ")]
    names = [re.search(r"(\w+)\s+__attribute__", t).group(1) for t in typedefs]
    rest = "\n".join(ln for ln in body.splitlines() if not ln.startswith("typedef "))
    helpers = re.findall(r"static inline [^{]*\{.*?\n\}", rest, flags=re.S)
    for h in helpers:
        rest = rest.replace(h, "")
    code = rest.strip()
    name = re.search(r"void\s+(\w+)\(", code).group(1)
    code = re.sub(rf"\b{name}\b", new_name, code)

    def pfx(t):
        return (
            re.sub(r"\b(" + "|".join(map(re.escape, names)) + r")\b", r"tg_\1", t)
            if names
            else t
        )

    return [pfx(t) for t in typedefs], [pfx(h) for h in helpers], pfx(code)


def pack(w: np.ndarray) -> np.ndarray:
    """W [K,N] -> Wp [N/32][K/4][32][4]: each 128-byte row is one vrmpy's 32 outputs x 4 K (the hand kernel's layout)."""
    K, N = w.shape
    return np.ascontiguousarray(w.reshape(K // 4, 4, N // 32, 32).transpose(2, 0, 3, 1))


def build(variant: str, x: np.ndarray, w: np.ndarray):
    captured.clear()
    if variant == "tcp":
        # the same GEMV over the prepacked weights: out[n] = sum_k x[k] * Wp[n/32, k/4, n%32, k%4]. Two reduce axes
        # (k/4, k%4) need TC_OPT=1; the vrmpy TC takes n%32 x k%4, i.e. one contiguous 128-byte weight vector per vrmpy
        K, N = w.shape
        with Context(TC_OPT=1):
            out = (
                (Tensor(x).reshape(1, K // 4, 1, 4) * Tensor(pack(w)))
                .sum((1, 3), dtype=dtypes.int32)
                .reshape(1, N)
            )
            got = out.realize().numpy()
        return got, list(captured)
    X, W = Tensor(x), Tensor(w)
    out = (
        X.matmul(W, dtype=dtypes.int32)
        if variant == "tc"
        else X.cast(dtypes.int32) @ W.cast(dtypes.int32)
    )
    got = out.realize().numpy()
    return got, list(captured)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--ops", default="up,down,qo,kv")
    ap.add_argument("--variants", default="tc,int32,tcp")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    typedefs, helpers, funcs = [], [], []
    rng = np.random.default_rng(0)
    for op in a.ops.split(","):
        K, N = SHAPES[op]
        x = rng.integers(0, 256, (1, K)).astype(np.uint8)
        w = rng.integers(-128, 128, (K, N)).astype(np.int8)
        ref = x.astype(np.int64) @ w.astype(np.int64)
        x.tofile(os.path.join(a.out, f"{op}_x.bin"))
        w.tofile(os.path.join(a.out, f"{op}_w.bin"))
        ref.astype(np.int32).tofile(os.path.join(a.out, f"{op}_ref.bin"))
        # the hand vrmpy kernel's layout: Wp[n/32][k/4][32 lanes][4] (each 128-byte vector = one k4 group
        # of 32 output columns), so one vrmpybusv per 128 weight bytes
        pack(w).tofile(os.path.join(a.out, f"{op}_wp.bin"))
        for v in a.variants.split(","):
            if op in PACKED_ONLY and v != "tcp":
                continue
            got, srcs = build(v, x, w)
            exact = bool(np.array_equal(got.astype(np.int64), ref))
            vr = any("vrmpy" in s for s in srcs)
            print(
                f"{op:5s} {v:5s} K={K} N={N} kernels={len(srcs)} vrmpy={vr} qemu exact={exact}"
            )
            if not exact:
                sys.exit(f"{op}/{v} not exact under qemu")
            if len(srcs) != 1:
                sys.exit(f"{op}/{v}: expected one kernel, got {len(srcs)}")
            td, hp, code = kernel_c(srcs[0], f"llm_{op}_{v}")
            typedefs += [t for t in td if t not in typedefs]
            helpers += [h for h in hp if h not in helpers]
            funcs.append(f"/* {op} ({K}x{N}), {v} */\n{code}")
    with open(os.path.join(a.out, "kernels.h"), "w") as f:
        f.write(
            "/* generated by llm_kernels.py -- do not edit */\n"
            + "\n".join(typedefs)
            + "\n\n"
            + "\n\n".join(helpers + funcs)
            + "\n"
        )
    print(f"wrote {a.out}/kernels.h")


if __name__ == "__main__":
    main()
