// Unit test for shapes.mjs -- reading a model's input/output dim_params out of
// the ONNX bytes with the dependency-free protobuf reader. Drives the exact
// same code the converter page's "Dynamic dimensions" panel uses. No network or
// browser needed.
//
//   node test/shapes.test.mjs
//
// The fixture (test/model.onnx, regenerated by test/make_fixture.py) has a
// symbolic batch axis: input X is [batch, 4] and output Y is [batch, 3].

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import assert from "node:assert/strict";
import {
  readShapes,
  formatDim,
  formatShape,
  isParamDim,
  dimParamNames,
  dimParamOccurrences,
  diffDimParams,
} from "../shapes.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const model = new Uint8Array(readFileSync(join(HERE, "model.onnx")));

let passed = 0;
function check(name, fn) {
  fn();
  passed += 1;
  console.log("  ok -", name);
}

const shapes = readShapes(model);
console.log("inputs:", JSON.stringify(shapes.inputs));
console.log("outputs:", JSON.stringify(shapes.outputs));

check("reads the graph input and output tensors", () => {
  assert.equal(shapes.inputs.length, 1, "one input (X)");
  assert.equal(shapes.outputs.length, 1, "one output (Y)");
  assert.equal(shapes.inputs[0].name, "X");
  assert.equal(shapes.outputs[0].name, "Y");
});

check("input X is [batch, 4] with a symbolic leading axis", () => {
  const shape = shapes.inputs[0].shape;
  assert.deepEqual(shape, [{ param: "batch" }, { value: 4 }]);
  assert.equal(isParamDim(shape[0]), true, "axis 0 is symbolic");
  assert.equal(isParamDim(shape[1]), false, "axis 1 is fixed");
});

check("output Y is [batch, 3]", () => {
  assert.deepEqual(shapes.outputs[0].shape, [{ param: "batch" }, { value: 3 }]);
});

check("formatDim / formatShape render axes readably", () => {
  assert.equal(formatDim({ param: "batch" }), "batch");
  assert.equal(formatDim({ value: 4 }), "4");
  assert.equal(formatDim({ unknown: true }), "?");
  assert.equal(formatDim(null), "?");
  assert.equal(formatShape(shapes.inputs[0].shape), "[batch, 4]");
  assert.equal(formatShape(null), "(unknown rank)");
  assert.equal(formatShape([]), "scalar");
});

check("dimParamNames lists each symbolic name once, in first-seen order", () => {
  assert.deepEqual(dimParamNames(shapes), ["batch"]);
});

check("dimParamOccurrences maps a name to every tensor axis it drives", () => {
  const occ = dimParamOccurrences(shapes);
  assert.deepEqual(occ.get("batch"), [
    { io: "input", tensor: "X", axis: 0 },
    { io: "output", tensor: "Y", axis: 0 },
  ]);
});

check("a model with no symbolic axes lists no dim_params", () => {
  const fixed = {
    inputs: [{ name: "X", shape: [{ value: 1 }, { value: 4 }] }],
    outputs: [{ name: "Y", shape: [{ value: 1 }, { value: 3 }] }],
  };
  assert.deepEqual(dimParamNames(fixed), []);
  assert.equal(dimParamOccurrences(fixed).size, 0);
});

check("unknown-rank / non-tensor values are skipped, not crashed on", () => {
  const weird = {
    inputs: [{ name: "seq", shape: null }, { name: "X", shape: [{ param: "n" }] }],
    outputs: [{ name: "Y", shape: [] }],
  };
  assert.deepEqual(dimParamNames(weird), ["n"]);
});

check("diffDimParams reports added / removed / common between two models", () => {
  const before = { inputs: [{ name: "X", shape: [{ param: "batch" }, { param: "seq" }] }], outputs: [] };
  const after = { inputs: [{ name: "X", shape: [{ param: "batch" }, { value: 128 }] }], outputs: [] };
  const d = diffDimParams(before, after);
  assert.deepEqual(d.before, ["batch", "seq"]);
  assert.deepEqual(d.after, ["batch"]);
  assert.deepEqual(d.common, ["batch"]);
  assert.deepEqual(d.removed, ["seq"], "seq became fixed (128) -> removed");
  assert.deepEqual(d.added, []);
});

console.log(`\nPASS: shapes.mjs read ${passed} checks worth of dim_param data from the model bytes`);
