/* DSP side: runs one captured kernel (qf_dispatch.h, generated by build.sh) `reps` times, single HVX thread, timed
 * on the DSP with HAP_perf_get_time_us. */
#include <stdlib.h>
#include "qf_rpc.h"
#include "qurt.h"
#include "HAP_power.h"
extern unsigned long long HAP_perf_get_time_us(void);
#include "qf_dispatch.h"

AEEResult qf_rpc_perf_vote(remote_handle64 h, int32 turbo, int32* rc) {
  HAP_power_request_t req = {0}; req.type = HAP_power_set_HVX; req.hvx.power_up = 1;
  *rc = HAP_power_set((void*)(uintptr_t)h, &req); return 0;
}
int qf_rpc_open(const char* uri, remote_handle64* h) { *h = (remote_handle64)(uintptr_t)malloc(1); return *h ? 0 : -1; }
int qf_rpc_close(remote_handle64 h) { if (h) free((void*)(uintptr_t)h); return 0; }
static int cmp_u64(const void* x, const void* y) {
  unsigned long long a = *(const unsigned long long*)x, b = *(const unsigned long long*)y; return a < b ? -1 : a > b;
}
AEEResult qf_rpc_run(remote_handle64 h, int32 kern, int32 reps, const unsigned char* b1, int n1, const unsigned char* b2, int n2,
                     const unsigned char* b3, int n3, const unsigned char* b4, int n4, const unsigned char* b5, int n5,
                     unsigned char* result, int nr, uint64* min_us, uint64* med_us) {
  if (kern < 0 || kern >= QF_NKERN || reps < 1 || reps > 64) return AEE_EBADPARM;
  void* bufs[6] = {result, (void*)b1, (void*)b2, (void*)b3, (void*)b4, (void*)b5};
  unsigned long long t[64];
  qurt_hvx_lock(QURT_HVX_MODE_128B);
  for (int r = 0; r < reps; r++) { unsigned long long t0 = HAP_perf_get_time_us(); qf_call(kern, bufs); t[r] = HAP_perf_get_time_us() - t0; }
  qurt_hvx_unlock();
  qsort(t, reps, sizeof t[0], cmp_u64); *min_us = t[0]; *med_us = t[reps / 2];
  return 0;
}
