// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE -- do not edit by hand. Produced by
//   python3 scripts/codegen/generate_moe_function_templates.py
// from the onnxscript function definitions in that script; see its
// module docstring for why this is checked in rather than generated
// on every build.
#ifndef ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_
#define ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_

namespace onnxsim {

constexpr const char* kMoERoutingHeadNormalize = R"MOE_TPL(
FlatShape = Constant <value_ints: ints = [-1, {{HIDDEN_SIZE}}]> ()
FlatInput = Reshape (input, FlatShape)
InputShape = Shape (input)
Probs = Softmax <axis: int = -1> (router_probs)
TopKConst = Constant <value_ints: ints = [{{K}}]> ()
TopVals, TopIdx = TopK <largest: int = 1, axis: int = -1> (Probs, TopKConst)
ReduceAxes = Constant <value_ints: ints = [-1]> ()
Denom = ReduceSum <keepdims: int = 1> (TopVals, ReduceAxes)
TopValsNorm = Div (TopVals, Denom)
ZeroT = Constant <value_float: float = 0.0> ()
ZeroCast = CastLike (ZeroT, input)
GateZeros = Mul (Probs, ZeroCast)
Gates = ScatterElements <axis: int = -1> (GateZeros, TopIdx, TopValsNorm)
GAxis = Constant <value_ints: ints = [1]> ()
SqueezeAxis = Constant <value_ints: ints = [0]> ()
Acc0 = Mul (FlatInput, ZeroCast)
)MOE_TPL";

constexpr const char* kMoERoutingHeadNoNormalize = R"MOE_TPL(
FlatShape = Constant <value_ints: ints = [-1, {{HIDDEN_SIZE}}]> ()
FlatInput = Reshape (input, FlatShape)
InputShape = Shape (input)
Probs = Softmax <axis: int = -1> (router_probs)
TopKConst = Constant <value_ints: ints = [{{K}}]> ()
TopVals, TopIdx = TopK <largest: int = 1, axis: int = -1> (Probs, TopKConst)
TopValsNorm = Identity (TopVals)
ZeroT = Constant <value_float: float = 0.0> ()
ZeroCast = CastLike (ZeroT, input)
GateZeros = Mul (Probs, ZeroCast)
Gates = ScatterElements <axis: int = -1> (GateZeros, TopIdx, TopValsNorm)
GAxis = Constant <value_ints: ints = [1]> ()
SqueezeAxis = Constant <value_ints: ints = [0]> ()
Acc0 = Mul (FlatInput, ZeroCast)
)MOE_TPL";

constexpr const char* kMoEExpertBlockReluFc1NoBiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
A1{{E}} = Relu (H1{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockReluFc1NoBiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
A1{{E}} = Relu (H1{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockReluFc1BiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
A1{{E}} = Relu (H1{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockReluFc1BiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
A1{{E}} = Relu (H1{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockIdentityFc1NoBiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
A1{{E}} = Identity (H1{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockIdentityFc1NoBiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
A1{{E}} = Identity (H1{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockIdentityFc1BiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
A1{{E}} = Identity (H1{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockIdentityFc1BiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
A1{{E}} = Identity (H1{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockSiluFc1NoBiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
Sig{{E}} = Sigmoid (H1{{E}})
A1{{E}} = Mul (H1{{E}}, Sig{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockSiluFc1NoBiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
Sig{{E}} = Sigmoid (H1{{E}})
A1{{E}} = Mul (H1{{E}}, Sig{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockSiluFc1BiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
Sig{{E}} = Sigmoid (H1{{E}})
A1{{E}} = Mul (H1{{E}}, Sig{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockSiluFc1BiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
Sig{{E}} = Sigmoid (H1{{E}})
A1{{E}} = Mul (H1{{E}}, Sig{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockGeluFc1NoBiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
Half{{E}} = Constant <value_float: float = 0.5> ()
HalfCast{{E}} = CastLike (Half{{E}}, H1{{E}})
One{{E}} = Constant <value_float: float = 1.0> ()
OneCast{{E}} = CastLike (One{{E}}, H1{{E}})
Two{{E}} = Constant <value_float: float = 2.0> ()
TwoCast{{E}} = CastLike (Two{{E}}, H1{{E}})
SqrtTwo{{E}} = Sqrt (TwoCast{{E}})
XSqrt{{E}} = Div (H1{{E}}, SqrtTwo{{E}})
ErfXSqrt{{E}} = Erf (XSqrt{{E}})
Phi{{E}} = Sum (OneCast{{E}}, ErfXSqrt{{E}})
MultX{{E}} = Mul (HalfCast{{E}}, H1{{E}})
A1{{E}} = Mul (MultX{{E}}, Phi{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockGeluFc1NoBiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}})
Half{{E}} = Constant <value_float: float = 0.5> ()
HalfCast{{E}} = CastLike (Half{{E}}, H1{{E}})
One{{E}} = Constant <value_float: float = 1.0> ()
OneCast{{E}} = CastLike (One{{E}}, H1{{E}})
Two{{E}} = Constant <value_float: float = 2.0> ()
TwoCast{{E}} = CastLike (Two{{E}}, H1{{E}})
SqrtTwo{{E}} = Sqrt (TwoCast{{E}})
XSqrt{{E}} = Div (H1{{E}}, SqrtTwo{{E}})
ErfXSqrt{{E}} = Erf (XSqrt{{E}})
Phi{{E}} = Sum (OneCast{{E}}, ErfXSqrt{{E}})
MultX{{E}} = Mul (HalfCast{{E}}, H1{{E}})
A1{{E}} = Mul (MultX{{E}}, Phi{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockGeluFc1BiasFc2NoBias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
Half{{E}} = Constant <value_float: float = 0.5> ()
HalfCast{{E}} = CastLike (Half{{E}}, H1{{E}})
One{{E}} = Constant <value_float: float = 1.0> ()
OneCast{{E}} = CastLike (One{{E}}, H1{{E}})
Two{{E}} = Constant <value_float: float = 2.0> ()
TwoCast{{E}} = CastLike (Two{{E}}, H1{{E}})
SqrtTwo{{E}} = Sqrt (TwoCast{{E}})
XSqrt{{E}} = Div (H1{{E}}, SqrtTwo{{E}})
ErfXSqrt{{E}} = Erf (XSqrt{{E}})
Phi{{E}} = Sum (OneCast{{E}}, ErfXSqrt{{E}})
MultX{{E}} = Mul (HalfCast{{E}}, H1{{E}})
A1{{E}} = Mul (MultX{{E}}, Phi{{E}})
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

constexpr const char* kMoEExpertBlockGeluFc1BiasFc2Bias = R"MOE_TPL(
W1Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W1_3d{{E}} = Gather <axis: int = 0> (fc1_experts_weights, W1Idx{{E}})
W1{{E}} = Squeeze (W1_3d{{E}}, SqueezeAxis)
W2Idx{{E}} = Constant <value_ints: ints = [{{E}}]> ()
W2_3d{{E}} = Gather <axis: int = 0> (fc2_experts_weights, W2Idx{{E}})
W2{{E}} = Squeeze (W2_3d{{E}}, SqueezeAxis)
B1_2d{{E}} = Gather <axis: int = 0> (fc1_experts_bias, W1Idx{{E}})
B1{{E}} = Squeeze (B1_2d{{E}}, SqueezeAxis)
H1{{E}} = Gemm <transB: int = 1> (FlatInput, W1{{E}}, B1{{E}})
Half{{E}} = Constant <value_float: float = 0.5> ()
HalfCast{{E}} = CastLike (Half{{E}}, H1{{E}})
One{{E}} = Constant <value_float: float = 1.0> ()
OneCast{{E}} = CastLike (One{{E}}, H1{{E}})
Two{{E}} = Constant <value_float: float = 2.0> ()
TwoCast{{E}} = CastLike (Two{{E}}, H1{{E}})
SqrtTwo{{E}} = Sqrt (TwoCast{{E}})
XSqrt{{E}} = Div (H1{{E}}, SqrtTwo{{E}})
ErfXSqrt{{E}} = Erf (XSqrt{{E}})
Phi{{E}} = Sum (OneCast{{E}}, ErfXSqrt{{E}})
MultX{{E}} = Mul (HalfCast{{E}}, H1{{E}})
A1{{E}} = Mul (MultX{{E}}, Phi{{E}})
B2_2d{{E}} = Gather <axis: int = 0> (fc2_experts_bias, W1Idx{{E}})
B2{{E}} = Squeeze (B2_2d{{E}}, SqueezeAxis)
Out{{E}} = Gemm <transB: int = 1> (A1{{E}}, W2{{E}}, B2{{E}})
GEnd{{E}} = Constant <value_ints: ints = [{{E1}}]> ()
GateCol{{E}} = Slice (Gates, W1Idx{{E}}, GEnd{{E}}, GAxis)
Weighted{{E}} = Mul (Out{{E}}, GateCol{{E}})
Acc{{E1}} = Add (Acc{{E}}, Weighted{{E}})
)MOE_TPL";

}  // namespace onnxsim

#endif  // ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_
