// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE -- do not edit by hand. Produced by
//   python3 scripts/codegen/generate_moe_function_templates.py
// from the onnxscript function definitions in that script; see its
// module docstring for what's generic (Loop over num_experts,
// attribute-forwarded k/normalize_routing_weights/use_sparse_mixer)
// vs. still fixed per variant (activation_type, bias presence) and
// why.
#ifndef ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_
#define ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_

namespace onnxsim {

constexpr const char* kMoEFunctionReluFc1NoBiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_39 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_38) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
a1 = Relu (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_38 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_39)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionReluFc1NoBiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
a1 = Relu (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionReluFc1BiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
a1 = Relu (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionReluFc1BiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_41 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_40) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
a1 = Relu (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_39 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_39)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_40 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_41)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionIdentityFc1NoBiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_39 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_38) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
a1 = Identity (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_38 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_39)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionIdentityFc1NoBiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
a1 = Identity (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionIdentityFc1BiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
a1 = Identity (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionIdentityFc1BiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_41 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_40) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
a1 = Identity (h1)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_39 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_39)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_40 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_41)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionSiluFc1NoBiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_39 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_38) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
sig = Sigmoid (h1)
a1 = Mul (h1, sig)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_38 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_39)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionSiluFc1NoBiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
sig = Sigmoid (h1)
a1 = Mul (h1, sig)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_37)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionSiluFc1BiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_40 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_39) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
sig = Sigmoid (h1)
a1 = Mul (h1, sig)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_39 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_40)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionSiluFc1BiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_41 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_40) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
sig = Sigmoid (h1)
a1 = Mul (h1, sig)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_38 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_38)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_39 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_39)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_40 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_41)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionGeluFc1NoBiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_41 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_40) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
c0 = Constant <value_float: float = 0.5> ()
c0_cast = CastLike (c0, h1)
c1 = Constant <value_float: float = 1.0> ()
c1_cast = CastLike (c1, h1)
c_coeff = Constant <value_float: float = 0.797885> ()
c_coeff_cast = CastLike (c_coeff, h1)
c_cube = Constant <value_float: float = 0.044715> ()
c_cube_cast = CastLike (c_cube, h1)
tmp_37 = Mul (h1, h1)
h1_cubed = Mul (tmp_37, h1)
tmp_38 = Mul (c_cube_cast, h1_cubed)
inner = Add (h1, tmp_38)
tanh_arg = Mul (c_coeff_cast, inner)
tanh_out = Tanh (tanh_arg)
one_plus_tanh = Add (c1_cast, tanh_out)
half_h1 = Mul (c0_cast, h1)
a1 = Mul (half_h1, one_plus_tanh)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_39 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_39)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_40 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_41)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionGeluFc1NoBiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_42 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_41) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
h1 = Gemm <transB: int = 1> (flat_input, w1)
c0 = Constant <value_float: float = 0.5> ()
c0_cast = CastLike (c0, h1)
c1 = Constant <value_float: float = 1.0> ()
c1_cast = CastLike (c1, h1)
c_coeff = Constant <value_float: float = 0.797885> ()
c_coeff_cast = CastLike (c_coeff, h1)
c_cube = Constant <value_float: float = 0.044715> ()
c_cube_cast = CastLike (c_cube, h1)
tmp_37 = Mul (h1, h1)
h1_cubed = Mul (tmp_37, h1)
tmp_38 = Mul (c_cube_cast, h1_cubed)
inner = Add (h1, tmp_38)
tanh_arg = Mul (c_coeff_cast, inner)
tanh_out = Tanh (tanh_arg)
one_plus_tanh = Add (c1_cast, tanh_out)
half_h1 = Mul (c0_cast, h1)
a1 = Mul (half_h1, one_plus_tanh)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_39 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_39)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_40 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_40)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_41 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_42)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionGeluFc1BiasFc2NoBias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_42 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_41) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
c0 = Constant <value_float: float = 0.5> ()
c0_cast = CastLike (c0, h1)
c1 = Constant <value_float: float = 1.0> ()
c1_cast = CastLike (c1, h1)
c_coeff = Constant <value_float: float = 0.797885> ()
c_coeff_cast = CastLike (c_coeff, h1)
c_cube = Constant <value_float: float = 0.044715> ()
c_cube_cast = CastLike (c_cube, h1)
tmp_38 = Mul (h1, h1)
h1_cubed = Mul (tmp_38, h1)
tmp_39 = Mul (c_cube_cast, h1_cubed)
inner = Add (h1, tmp_39)
tanh_arg = Mul (c_coeff_cast, inner)
tanh_out = Tanh (tanh_arg)
one_plus_tanh = Add (c1_cast, tanh_out)
half_h1 = Mul (c0_cast, h1)
a1 = Mul (half_h1, one_plus_tanh)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_40 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_40)
out = Gemm <transB: int = 1> (a1, w2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_41 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_42)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

constexpr const char* kMoEFunctionGeluFc1BiasFc2Bias = R"MOE_TPL(
hidden_shape = Shape <start: int = 2> (fc1_experts_weights)
neg_one = Constant <value_ints: ints = [-1]> ()
flat_shape = Concat <axis: int = 0> (neg_one, hidden_shape)
flat_input = Reshape (input, flat_shape)
input_shape = Shape (input)
num_experts_1d = Shape <end: int = 1, start: int = 0> (fc1_experts_weights)
num_experts = Squeeze (num_experts_1d)
probs = Softmax <axis: int = -1> (router_probs)
k_i = Constant <value_int: int = @k> ()
tmp = Constant <value_ints: ints = [0]> ()
k_1d = Unsqueeze (k_i, tmp)
top_vals, top_idx = TopK <largest: int = 1, axis: int = -1> (probs, k_1d)
reduce_axes = Constant <value_ints: ints = [-1]> ()
zero_f = Constant <value_float: float = 0.0> ()
zero_cast = CastLike (zero_f, input)
normalize_i = Constant <value_int: int = @normalize_routing_weights> ()
normalize_flag = Cast <to: int = 9> (normalize_i)
top_vals_norm_1 = If (normalize_flag) <then_branch: graph = thenGraph_19 () => ( top_vals_norm) {
denom = ReduceSum <keepdims: int = 1> (top_vals, reduce_axes)
top_vals_norm = Div (top_vals, denom)
   }, else_branch: graph = elseGraph_19 () => ( top_vals_norm_0) {
top_vals_norm_0 = Identity (top_vals)
   }>
gate_zeros = Mul (probs, zero_cast)
softmax_gates = ScatterElements <axis: int = -1> (gate_zeros, top_idx, top_vals_norm_1)
two_i = Constant <value_ints: ints = [2]> ()
sm_top_vals, sm_top_idx = TopK <largest: int = 1, axis: int = -1> (router_probs, two_i)
tmp_2 = Constant <value_ints: ints = [0]> ()
tmp_3 = Constant <value_ints: ints = [1]> ()
tmp_4 = Constant <value_ints: ints = [-1]> ()
sm_val0 = Slice (sm_top_vals, tmp_2, tmp_3, tmp_4)
tmp_5 = Constant <value_ints: ints = [1]> ()
tmp_6 = Constant <value_ints: ints = [2]> ()
tmp_7 = Constant <value_ints: ints = [-1]> ()
sm_val1 = Slice (sm_top_vals, tmp_5, tmp_6, tmp_7)
tmp_8 = Constant <value_ints: ints = [0]> ()
tmp_9 = Constant <value_ints: ints = [1]> ()
tmp_10 = Constant <value_ints: ints = [-1]> ()
sm_idx0 = Slice (sm_top_idx, tmp_8, tmp_9, tmp_10)
tmp_11 = Constant <value_ints: ints = [1]> ()
tmp_12 = Constant <value_ints: ints = [2]> ()
tmp_13 = Constant <value_ints: ints = [-1]> ()
sm_idx1 = Slice (sm_top_idx, tmp_11, tmp_12, tmp_13)
sm_jitter = Constant <value_float: float = 0.02> ()
sm_jitter_cast = CastLike (sm_jitter, router_probs)
tmp_14 = Abs (router_probs)
sm_factor0 = Max (tmp_14, sm_val0)
tmp_15 = Sub (sm_val0, router_probs)
tmp_16 = Mul (sm_jitter_cast, sm_factor0)
sm_mask0 = Greater (tmp_15, tmp_16)
tmp_17 = Constant <value_float: float = 0.0> ()
sm_zero = CastLike (tmp_17, router_probs)
tmp_18 = Sub (router_probs, sm_val0)
sm_exp0 = Exp (tmp_18)
tmp_19 = Where (sm_mask0, sm_zero, sm_exp0)
sm_denom0 = ReduceSum <keepdims: int = 1> (tmp_19, reduce_axes)
tmp_20 = Constant <value_float: float = 1.0> ()
sm_one = CastLike (tmp_20, router_probs)
sm_w0 = Div (sm_one, sm_denom0)
tmp_21 = Abs (router_probs)
sm_factor1 = Max (tmp_21, sm_val1)
tmp_22 = Sub (sm_val1, router_probs)
tmp_23 = Mul (sm_jitter_cast, sm_factor1)
sm_mask1_raw = Greater (tmp_22, tmp_23)
tmp_24 = Constant <value_int: int = 0> ()
tmp_25 = Shape <start: int = -1> (router_probs)
tmp_26 = Squeeze (tmp_25)
tmp_27 = Constant <value_int: int = 1> ()
sm_arange = Range (tmp_24, tmp_26, tmp_27)
tmp_28 = Cast <to: int = 7> (sm_arange)
tmp_29 = Cast <to: int = 7> (sm_idx0)
sm_is_idx0 = Equal (tmp_28, tmp_29)
sm_mask1 = Or (sm_mask1_raw, sm_is_idx0)
tmp_30 = Sub (router_probs, sm_val1)
sm_exp1 = Exp (tmp_30)
tmp_31 = Where (sm_mask1, sm_zero, sm_exp1)
sm_denom1 = ReduceSum <keepdims: int = 1> (tmp_31, reduce_axes)
sm_w1 = Div (sm_one, sm_denom1)
sm_zero_row = Mul (router_probs, sm_zero)
sm_w_pair = Concat <axis: int = -1> (sm_w0, sm_w1)
sm_idx_pair = Concat <axis: int = -1> (sm_idx0, sm_idx1)
sparse_mixer_gates = ScatterElements <axis: int = -1> (sm_zero_row, sm_idx_pair, sm_w_pair)
sparse_mixer_i = Constant <value_int: int = @use_sparse_mixer> ()
sparse_mixer_flag = Cast <to: int = 9> (sparse_mixer_i)
gates_33 = If (sparse_mixer_flag) <then_branch: graph = thenGraph_57 () => ( gates) {
gates = Identity (sparse_mixer_gates)
   }, else_branch: graph = elseGraph_57 () => ( gates_32) {
gates_32 = Identity (softmax_gates)
   }>
acc_final = Mul (flat_input, zero_cast)
acc_final_43 = Loop (num_experts, "", acc_final) <body: graph = loop_body (int64 e, bool cond_in,  acc_final_34) => ( cond_out,  acc_final_42) {
tmp_35 = Constant <value_ints: ints = [1]> ()
e_idx = Reshape (e, tmp_35)
w1_3d = Gather <axis: int = 0> (fc1_experts_weights, e_idx)
tmp_36 = Constant <value_ints: ints = [0]> ()
w1 = Squeeze (w1_3d, tmp_36)
b1_2d = Gather <axis: int = 0> (fc1_experts_bias, e_idx)
tmp_37 = Constant <value_ints: ints = [0]> ()
b1 = Squeeze (b1_2d, tmp_37)
h1 = Gemm <transB: int = 1> (flat_input, w1, b1)
c0 = Constant <value_float: float = 0.5> ()
c0_cast = CastLike (c0, h1)
c1 = Constant <value_float: float = 1.0> ()
c1_cast = CastLike (c1, h1)
c_coeff = Constant <value_float: float = 0.797885> ()
c_coeff_cast = CastLike (c_coeff, h1)
c_cube = Constant <value_float: float = 0.044715> ()
c_cube_cast = CastLike (c_cube, h1)
tmp_38 = Mul (h1, h1)
h1_cubed = Mul (tmp_38, h1)
tmp_39 = Mul (c_cube_cast, h1_cubed)
inner = Add (h1, tmp_39)
tanh_arg = Mul (c_coeff_cast, inner)
tanh_out = Tanh (tanh_arg)
one_plus_tanh = Add (c1_cast, tanh_out)
half_h1 = Mul (c0_cast, h1)
a1 = Mul (half_h1, one_plus_tanh)
w2_3d = Gather <axis: int = 0> (fc2_experts_weights, e_idx)
tmp_40 = Constant <value_ints: ints = [0]> ()
w2 = Squeeze (w2_3d, tmp_40)
b2_2d = Gather <axis: int = 0> (fc2_experts_bias, e_idx)
tmp_41 = Constant <value_ints: ints = [0]> ()
b2 = Squeeze (b2_2d, tmp_41)
out = Gemm <transB: int = 1> (a1, w2, b2)
gate_col = Gather <axis: int = 1> (gates_33, e_idx)
weighted = Mul (out, gate_col)
acc_final_42 = Add (acc_final_34, weighted)
cond_out = Identity (cond_in)
   }>
flat_output = Identity (acc_final_43)
output = Reshape (flat_output, input_shape)
)MOE_TPL";

}  // namespace onnxsim

#endif  // ONNXSIM_CONTRIB_SCHEMAS_MOE_TEMPLATES_GEN_H_
